### ISSUE TITLE
Offsetting room adjust causes avatar calibration offsets 

### ISSUE THREAD

**Issue by 1FCZ1LoneWolf** [nicoco007/BeatSaberCustomAvatars#102]
moving the room adjust from the center off the steam VR playspace causes the avatar to offset in the direction of where ever the center of your steamVR playspace is while callibrating.

standing where the avatars feet show causes rotational offsets proptional to distance from center.

issue occuring with multiple custom avatars exported from unity using exactly 0.0.0 project positioning and correctly aligned targets/constraints and IK tweeking.

**Comment by nicoco007** [comment]
Yeah, I noticed that while investigating #99 (basically the same issue). I'll make sure to get it fixed for the next release.

**Comment by nicoco007** [comment]
Fixed by 42ec0f2 which will be included in the next release. Thanks for the bug report!
