### ISSUE TITLE
custom avatar menu is not displayed

### ISSUE THREAD

**Issue by lairro** [nicoco007/BeatSaberCustomAvatars#108]
**Before doing anything else, please attach your latest log to this issue. It should be located at `Logs\_latest.log` in your Beat Saber installation's folder.**

**Desktop (please complete the following information):**
- Operating system: windows 10
- Headset and controllers: oculus quest 2
- Beat Saber version: 1.16.1
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/6620991/_latest.log)

**Describe the bug**
I had to do a clean installation and now it does not show me the custom avatar menu in the main menu

**Steps to reproduce**
1. Installed DynamicOpenVR (manually)
2. Installed DynamicOpenVR.BeatSaber (manually)
3. Installed Custom Avatar (manually)
4. Open Beat Saber
5. the custom avatar button does not appear in the main menu

**Expected behavior**
be able to see the custom avatar button

**Screenshots**
![Captura](https://user-images.githubusercontent.com/20462884/121290843-4eb43200-c8b5-11eb-9fd4-96834889a063.PNG)

**Comment by nicoco007** [comment]
According to the log you provided, DynamicOpenVR isn't actually installed. Are you sure you copied all the files over?

**Comment by lairro** [comment]
install the latest versions in fact download another mod to download avatars and it tells me that I don't have the custom avatar installed but I have it in the plugin folder

**Comment by lairro** [comment]
![1](https://user-images.githubusercontent.com/20462884/121293891-6c37ca80-c8ba-11eb-8966-61e4ff905222.PNG)
![2](https://user-images.githubusercontent.com/20462884/121293894-6e018e00-c8ba-11eb-96c5-5164cc38817f.PNG)
![3](https://user-images.githubusercontent.com/20462884/121293896-6fcb5180-c8ba-11eb-9e4d-7f4bb8d39ce8.PNG)

**Comment by lairro** [comment]
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/6621143/_latest.log)
I reinstalled everything manually and I still have the problem

**Comment by lairro** [comment]
You were right, now that I check the log well I see that the DynamicOpenVR is not installed but I know that it is in the folder and I run the ipa but I do not know why it does not install it

**Comment by lairro** [comment]
I finally found the problem, I was missing some dll in plugin the "DynamicOpenVR.manifest" and in lib the "DynamicOpenVR.dll" and it did not say anywhere that it should leave those two files 😅😅😅

**Comment by lairro** [comment]
I finally found the problem, I was missing some dll in plugin the "DynamicOpenVR.manifest" and in lib the "DynamicOpenVR.dll"  😅😅😅

**Comment by nicoco007** [comment]
Glad you were able to figure it out!
