### ISSUE TITLE
Mod doesn't show in ModAssistant

### ISSUE THREAD

**Issue by realdeadbeef** [nicoco007/BeatSaberCustomAvatars#109]
Hello there but the mod doesn't show up in ModAssistant.
I have attached a screenshot of what mine looks like.

![image](https://user-images.githubusercontent.com/64917571/122647869-457d5d80-d11e-11eb-92ce-567949e4e54c.png)

Thanks, Tom.

**Comment by nicoco007** [comment]
I submitted it for approval just over a week ago and it is currently in queue so unfortunately this is beyond my control. All I can do at this point is wait.

For future reference, Custom Avatars is always under the "Cosmetic" category once it's approved.

**Comment by realdeadbeef** [comment]
Thanks for the help! I'll keep an eye out.

**Comment by nicoco007** [comment]
Alright so 5.2.5 was approved but I asked for it to be held back because of the issues described in #110. I'll be uploading 5.2.6 soon with not a lot of changes so it should be approved pretty fast.

**Comment by realdeadbeef** [comment]
Okay thank you, I'll try the one with supposed bugs but will upgrade when the new one comes out. Thanks for the help!

**Comment by nicoco007** [comment]
Version 5.2.6 is now available on ModAssistant. Thank you for your patience!
