### ISSUE TITLE
Avatars not showing up in the avatar menu

### ISSUE THREAD

**Issue by MrGatlampa** [nicoco007/BeatSaberCustomAvatars#11]
So My IQ is in the negatives and im really bad at understanding this kind of computer stuff so i apologize if my explenations are really bad or if there even will be explenations since i dont understand half of this stuff ಠ_ಠ. And I literally made this github account just to I could try to get some help...

[log.txt](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4158925/message.txt)

So when I go into the avatar menu I see three avatars, two "template" avatars that came when i downloaded the mod, and one that i have made myself, when I click on one (happens with all three) nothing shows, i have the option called something like "show avatar in first person" turned on but i still dont see anything in front of me

1. Go to the avatar options located in the left "screen"
2. Click on whatever avatar you want
3. no avatar showing up in front of you

**Expected behavior**
the avatar showing up when i select one, i dont know if this matters at all but i have the camera+ mod and the avatar dosent appear in third person there either

**Screenshots**
![Anteckning_2020-02-05_115117](https://user-images.githubusercontent.com/60693722/73835878-7d784f00-480e-11ea-9827-4a478ae666f2.png)
![Anteckning_2020-02-05_115319](https://user-images.githubusercontent.com/60693722/73835885-810bd600-480e-11ea-8529-a20b3361e2ef.png)
![Anteckning_2020-02-05_115338](https://user-images.githubusercontent.com/60693722/73835891-836e3000-480e-11ea-956d-de4b39737db2.png)

**Desktop (please complete the following information):**
- Operating system: Windows 10

im sorry if this is a really easy issue, as i said before im not good with this stuff at all, relating to that, if you think you know how this issue can be fixed, please explain with excruciatingly much detail since im absolutely horrible at understanding instructions, sorry for the inconveniance.

thanks in advance, please tell me if you are missing some important information

**Comment by nicoco007** [comment]
No worries! You provided a lot of valuable information so I'm very grateful for that 😃 

It just looks like you haven't installed DynamicOpenVR. You can download it [over here](https://github.com/nicoco007/DynamicOpenVR/releases/tag/v0.1.1) and there are some [basic installation instructions](https://github.com/nicoco007/DynamicOpenVR#installing) you can follow if you're not sure how to install it.

Let me know if something is unclear or if you have any other issues!

**Comment by MrGatlampa** [comment]
> 
> 
> No worries! You provided a lot of valuable information so I'm very grateful for that 😃
> 
> It just looks like you haven't installed DynamicOpenVR. You can download it [over here](https://github.com/nicoco007/DynamicOpenVR/releases/tag/v0.1.1) and there are some [basic installation instructions](https://github.com/nicoco007/DynamicOpenVR#installing) you can follow if you're not sure how to install it.
> 
> Let me know if something is unclear or if you have any other issues!

alright it worked! now the template avatar is showing up! but now i have a different problem... i cant point with my controller and thus cant click any buttons on the screen, thats why i specificaly said template avatar sicne it automaticly loaded in when i opend the game, strangely enough i could clikc on the warning menu that appears when you launch the game, but after that the laser pointer thing didnt show up efen tho i pressed the trigger (i tried on both controllers) ¯\_(ツ)_/¯, thanks in advance! (again ᕕ( ᐛ )ᕗ)

**Comment by Aloki** [comment]
I have the same problem. After updating to version 5.0.0 beta 6, the trigger button stopped working. I have an Index Controllers.

**Comment by nicoco007** [comment]
Could you check out the [troubleshooting guide](https://github.com/nicoco007/DynamicOpenVR/blob/master/TROUBLESHOOTING.md) and follow both the *Checking the installation* and *Buttons and/or tracking aren't working properly* sections and let me know how that goes?

Also @MrGatlampa could you let me know what headset you're using (Vive/Rift/Index/WMR/etc.) ?

**Comment by MrGatlampa** [comment]
> Could you check out the [troubleshooting guide](https://github.com/nicoco007/DynamicOpenVR/blob/master/TROUBLESHOOTING.md) and follow both the _Checking the installation_ and _Buttons and/or tracking aren't working properly_ sections and let me know how that goes?
> 
> Also @MrGatlampa could you let me know what headset you're using (Vive/Rift/Index/WMR/etc.) ?

Sadly I cant really do that right now but I can atleast say that I am using a Vive with normal vive wand controllers

**Comment by nicoco007** [comment]
Actually, nevermind for now - someone else is having a similar issue over at nicoco007/DynamicOpenVR#16. It looks like it may not be related to bindings.

**Comment by nicoco007** [comment]
This version of DynamicOpenVR fixed the issue for the person mentioned above. Could you try it when you get the chance?

[DynamicOpenVR.BeatSaber-b86f25b-RELEASE.zip](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4162610/DynamicOpenVR.BeatSaber-b86f25b-RELEASE.zip)

**Comment by MrGatlampa** [comment]
> 
> 
> This version of DynamicOpenVR fixed the issue for the person mentioned above. Could you try it when you get the chance?
> 
> [DynamicOpenVR.BeatSaber-b86f25b-RELEASE.zip](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4162610/DynamicOpenVR.BeatSaber-b86f25b-RELEASE.zip)

huh it started working without me doing anything?! i just relaunched the game and now everything works ¯\_(ツ)_/¯, now i can finally record cool looking beat saber videos! thank you so much for the help!

**Comment by nicoco007** [comment]
Great! I'll close this issue since it seems to be resolved. If you run into any other problems, feel free to open a new issue.
