### ISSUE TITLE
the game crashes on the menu 

### ISSUE THREAD

**Issue by rickshadow** [nicoco007/BeatSaberCustomAvatars#110]
**Before doing anything else, please attach your latest log to this issue. It should be located at `Logs\_latest.log` in your Beat Saber installation's folder.**

**Desktop (please complete the following information):**
- Operating system: [e.g. Windows 10, Ubuntu 18.04]
- Headset and controllers: [e.g. Oculus Rift, HTC Vive, Valve Index]

**Describe the bug**
A clear and concise description of what the bug is. If your issue occurs with a particular avatar, please add a link to where you found it or attach it; **please do not attach the avatar file to this issue if you did not create it**.

**Steps to reproduce**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Comment by nicoco007** [comment]
Hi! Could you please fill out the issue description with the requested details? I unfortunately cannot help you much with just the title you provided.

**Comment by rickshadow** [comment]
I'm on valve index and it shows up on the mods tab in beat saber and everything but when i click on the mod to pick an avatar the game lags out and crashes

**Comment by rickshadow** [comment]
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/6688625/_latest.log)

**Comment by Kiritosblade** [comment]
I've actually been experiencing the same issue with my index, whenever i open the custom avatars menu screen to calibrate/change avatar it's like running at 1fps if even. Also valve index, index thing maybe?

**Comment by Kiritosblade** [comment]
Actually there's a solution to the problem, completely turn off antialiasing (msaa). That mirror in avatar screen is the problem i think. But anyways yeah turn off aa, it stopped lagging entirely after i did so

**Comment by nicoco007** [comment]
@rickshadow Thanks for the info!

@Kiritosblade Good to know! I suspected that the mirror might be the problem. I had made some changes to it for 5.2.4 but I've reverted those since they're obviously causing problems. I'll publish a new release with this fixed ASAP.

**Comment by nicoco007** [comment]
This should now be fixed in [version 5.2.6](https://github.com/nicoco007/BeatSaberCustomAvatars/releases/tag/v5.2.6). Please let me know if that's the case or if you're still running into problems.

**Comment by nicoco007** [comment]
Since I haven't had news from anyone here and have been told by other people who had the problem previously and said it was no longer the case with 5.2.6, I'm going to assume this has been fixed and close this issue. Feel free to open a new one if you're still having trouble.
