### ISSUE TITLE
Infinite Loading

### ISSUE THREAD

**Issue by Norradus** [nicoco007/BeatSaberCustomAvatars#111]
**Before doing anything else, please attach your latest log to this issue. It should be located at `Logs\_latest.log` in your Beat Saber installation's folder.**

**Desktop (please complete the following information):**
- Operating system: [Windows 10,Ryzen 5 3600 6-Core 3,6GHz, 16GB DDR4 Ram, Nvidia Geforce RTX 3060 Ti ]
- Headset and controllers: [Oculus Rift S]

**Describe the bug**
When i click on ''Avatars'' in the Main Menu an Hourglass is showing and it starts and infinite Loading Extreme Laggy i can click nothing the Avatar is showing up and fading away over and over again in only can ALT+F4 the Game
**Steps to reproduce**
1. Main Menu
2. Click on Avatars
3. Hourglass showing (Games Loading)
4. Infinite Loading with Extreme Laggs

**Expected behavior**
No Laggs and Faster Loading i guess? :D

[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/6703936/_latest.log)

EDIT: NVM Got i Fixed by Setting Antialiasing to 0 :D

**Comment by nicoco007** [comment]
> EDIT: NVM Got i Fixed by Setting Antialiasing to 0 :D

Alright, this is probably the same as #110 then; I'll close this and post updates there. Thanks for the report!
