### ISSUE TITLE
Unity BeatSaberCustomAvatar doesnt work 

### ISSUE THREAD

**Issue by SLDDL** [nicoco007/BeatSaberCustomAvatars#112]
Operating system: Windows 10
Headset and controllers: Oculus Quest 2 using Link

I created an avatar using the unity template in the release, i can select it but its invisible in game, i then tried to export the full body template and it was invisible too.

Export an avatar using https://github.com/nicoco007/BeatSaberCustomAvatars/releases/download/v5.2.5/BeatSaberCustomAvatars-v5.2.5-UnityProject.zip and unity 2019

Expected behavior:
The avatar exports correctly and works in game

Screenshots and files:

Behavior :  https://dl.dropboxusercontent.com/s/8h8a9cofzm8ni77/2xOp5h5Rgb.mp4
( Fullbody test is the fullbody template that i exported )
( zhongli is the avatar im trying to make ) 

Logs : [_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/6716254/_latest.log)

Avatar files : https://drive.google.com/drive/folders/1MQOtVxpGQVWFFmVSF8pbEkaQ0t12BYUT?usp=sharing

Unity Project : https://drive.google.com/file/d/1UpYJkNCRkEmFN8y-3v0fy-7rXC_yl94V/view?usp=sharing

**Comment by nicoco007** [comment]
Looks like you're using Unity 2019.4.28f1 instead of 2019.4.18f1. I was able to export your avatar successfully on my end using 2019.4.18f1 so could you try again using that version? You can get it from [the Unity Download Archive](https://unity3d.com/fr/get-unity/download/archive).

**Comment by SLDDL** [comment]
wow thanks!!
