### ISSUE TITLE
Manual arm span

### ISSUE THREAD

**Issue by SLDDL** [nicoco007/BeatSaberCustomAvatars#115]
I've noticed that when i have my arms outward, my quest 2 doesn't recognize both controllers at the same time so it's complicated to have a correct arm span for the model size

Being able to manually set the arm span would fix this issue

**Comment by nicoco007** [comment]
I hadn't thought of that problem. I'll see what I can do!

**Comment by nicoco007** [comment]
Added by c1c338d20decee94644f169e3755a5198b3a338a which will be included in the next release. Thanks for the suggestion!

![Manual arm span](https://user-images.githubusercontent.com/1349975/126392860-121ce982-3bd7-4da2-a11e-cf8a632cf3d9.png)
