### ISSUE TITLE
Doesn't load on 1.16.2

### ISSUE THREAD

**Issue by headassbtw** [nicoco007/BeatSaberCustomAvatars#116]
**Desktop:**
- Operating system: Manjaro linux 5.10.42-1
- Headset and controllers: Valve Index

**Describe the bug**
CustomAvatars (and DynamicOpenVR.BeatSaber) do not load

**Steps to reproduce**
1. Download the latest releases of CustomAvatars, DynamicOpenVR, and DynamicOpenVR.BeatSaber
2. Launch the game
3. Suffer

**Expected behavior**
I expected it to load the plugin

Log:
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/6773986/_latest.log)

**Comment by headassbtw** [comment]
of note: this still happens when i remove DynamicOpenVR.BeatSaber

**Comment by nicoco007** [comment]
Looks like the DLL is outright not able to load:

```
[CRITICAL @ 20:04:09 | IPA] Uncaught exception while loading pluign Custom Avatars:
[CRITICAL @ 20:04:09 | IPA] System.BadImageFormatException: 
[CRITICAL @ 20:04:09 | IPA] File name: 'Z:\home\headass\Steam\steamapps\common\Beat Saber\Plugins\CustomAvatar.dll'
[CRITICAL @ 20:04:09 | IPA]   at (wrapper managed-to-native) System.Reflection.Assembly.LoadFrom(string,bool)
[CRITICAL @ 20:04:09 | IPA]   at System.Reflection.Assembly.LoadFrom (System.String assemblyFile) [0x00000] in <9577ac7a62ef43179789031239ba8798>:0 
[CRITICAL @ 20:04:09 | IPA]   at IPA.Loader.PluginLoader.Load (IPA.Loader.PluginMetadata meta) [0x00016] in Z:\Users\aaron\Source\Repos\IPA-Reloaded-BeatSaber\IPA.Loader\Loader\PluginLoader.cs:780 
[CRITICAL @ 20:04:09 | IPA]   at IPA.Loader.PluginLoader.InitPlugin (IPA.Loader.PluginMetadata meta, System.Collections.Generic.IEnumerable`1[T] alreadyLoaded) [0x00117] in Z:\Users\aaron\Source\Repos\IPA-Reloaded-BeatSaber\IPA.Loader\Loader\PluginLoader.cs:820 
[CRITICAL @ 20:04:09 | IPA]   at IPA.Loader.PluginLoader.LoadPlugins () [0x00037] in Z:\Users\aaron\Source\Repos\IPA-Reloaded-BeatSaber\IPA.Loader\Loader\PluginLoader.cs:904 
```

I've never seen this before so I don't know exactly what's causing it, but I'm guessing it's either
1. The DLL is corrupt, or
2. Proton/Wine/whatever you're using to load the game on Linux doesn't like the DLL for some reason.

Did this happen with any of the previous versions of Custom Avatars? Could you try re-downloading and re-installing the latest release?

**Comment by headassbtw** [comment]
it did not happen with a previous version (the ones on BeatMods)
i've already tried re-downloading the new ones as well, 

of note: i'm using proton 5.13-6

**Comment by headassbtw** [comment]
i've been told it's because it needs to be compiled for x64, but idk if that's true

**Comment by headassbtw** [comment]
just confirmed, not being compiled for x64 is the problem

**Comment by nicoco007** [comment]
Interesting. I guess I should just release for x64 in the future since the game is 64-bit so Any CPU isn't necessary/useful.
