### ISSUE TITLE
make avatars follow replay

### ISSUE THREAD

**Issue by gianludoge** [nicoco007/BeatSaberCustomAvatars#117]
**Is your feature request related to a problem? Please describe.**
when i register replays the avatar does not follow the replay

**Describe the solution you'd like**
if the avatar follows the replay i could register the same play in different positions

**Comment by nicoco007** [comment]
This is something I have thought of in the past. Unfortunately, this probably won't happen for a while (or maybe even ever) for two main reasons:

1. For security reasons, the ScoreSaber plugin is not open-source and is obfuscated (meaning it's essentially impossible to get the code back from the published plugin), so it would be technically very difficult to drop an avatar on top of the replay; and
2. Umbranox (main author/maintainer of ScoreSaber) has made it clear that they want it to be as obvious as possible when a replay is running. Having an avatar follow the replay would make it harder to tell, so unless I get explicit approval I won't be adding this as a feature.

If the situation ever changes I will post an update here, but for the time being I will be closing this issue.
