### ISSUE TITLE
Manual floor height offset

### ISSUE THREAD

**Issue by SLDDL** [nicoco007/BeatSaberCustomAvatars#118]
**Is your feature request related to a problem? Please describe.**
I use an avatar of Zhongli from genshin impact, he's tall but im not.

When i set the scale to height, he's small like a toddler and when i do arm span, the size is correct but he's crouching.

i can fix that by making the arm span bigger with my previous feature request but it makes so when i have my arms fully extended the avatar doesn't and has them bent, a lot

**Describe the solution you'd like**
I would like to have an option to manually change the floor height without changing the model size

**Comment by nicoco007** [comment]
Both of those issues are usually caused by your player height not being set to your true height. Have you tried disabling automatic height and setting your height manually in Player Settings?

**Comment by nicoco007** [comment]
Closing this since there has been no response for a while. Feel free to open a new issue if you're still having problems.
