### ISSUE TITLE
Triggers fail to work. (WMR, Samsung HMD Odyssey+)

### ISSUE THREAD

**Issue by foodcakegameboycolour** [nicoco007/BeatSaberCustomAvatars#12]
**Before doing anything else, please attach your latest log to this issue.**
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4202599/_latest.log)

**Describe the bug**
Any time that I select an avatar in the Avatar menu, my triggers stop working and I have to remove all models to continue to play. Model shows up, tracking works, everything is fine, besides not being able to use the triggers.

**Steps to reproduce**
1. Go to your beat saber installation folder, install latest CustomAvatars and DynamicOpenVR.
2. Click on the Beat Saber.exe to launch
3. Open the mods tab on your left, click avatars.
4. Select any avatar, triggers stop working.

**Expected behavior**
Just as before, except bindings work.

**Desktop (please complete the following information):**
- Operating system: Windows 10 Home
-HMD + Controllers: Samsung HMD Odyssey+

**Comment by foodcakegameboycolour** [comment]
I forgot to say that I tried all troubleshooting steps dealing with binds, went back into solved issues and tried binds that were attached there, nothing.

**Comment by nicoco007** [comment]
Could you try [this build](https://ci.gnyra.com/job/DynamicOpenVR/job/master/115/artifact/DynamicOpenVR.BeatSaber-3128992-RELEASE.zip) of DynamicOpenVR and let me know if it works? If it doesn't, could you attach your latest log after running the game with it?

**Comment by foodcakegameboycolour** [comment]
My bindings don't register, I can only select legacy bindings and my controller tracking doesn't work
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4234183/_latest.log)
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4234184/_latest.log)

**Comment by nonstopreapers** [comment]
I have the same problem, any avatar I select will freeze the trigger and I would have to uninstall the avatar for trigger to work again

**Comment by nicoco007** [comment]
Sorry for taking so long to respond. This will be fixed in the next release, which should be available in the next few days.

**Comment by sergioromerohd** [comment]
i use rift S i got the same problem but i can solve it with the build u send before

**Comment by nicoco007** [comment]
I just released [Custom Avatars](https://github.com/nicoco007/BeatSaberCustomAvatars/releases/tag/v5.0.0-beta.7) and [DynamicOpenVR](
https://github.com/nicoco007/DynamicOpenVR/releases/tag/v0.2.0) for Beat Saber 1.8.0. Could you try installing Custom Avatars and DynamicOpenVR but not DynamicOpenVR.BeatSaber and let me know if that works?
