### ISSUE TITLE
Mods missing from mod assistant

### ISSUE THREAD

**Issue by Sk8erBoiCyaL8erBoi** [nicoco007/BeatSaberCustomAvatars#121]
I used to have the custom sabers mod, the custom avatars mod among others that were in mod assistant but, today I opened after a while of not playing beat saber and they were all missing. I have went through the process of installing the files into the beat saber file but they still don't show up at all. I don't know if its just not working at the moment or I'm doing something wrong. I've watched videos on how to install custom avatars and I've done everything step by step and the only mods I see in game are the camera 2 and songcore. I can install avatars into the avatars folder but I don't see the option to change avatar in game. I've made sure to use all the up to date files and updated my game too.

**Comment by nicoco007** [comment]
I've submitted Custom Avatars for approval and it will hopefully be available on ModAssistant within the next 24 hours.

If you still want to install it manually, here are some pointers:
- Make sure you have the latest versions of SiraUtil and BeatSaberMarkupLanguage from ModAssistant.
- Check you've installed both [the latest release of DynamicOpenVR](https://github.com/nicoco007/DynamicOpenVR/releases/latest) and [the latest release of Custom Avatars](https://github.com/nicoco007/BeatSaberCustomAvatars/releases/latest) properly by making sure you have **all** the files and folders from the ZIP in your Beat Saber folder (not just the DLLs).

For more specific help, I'm going to need your latest log (the file called `_latest.log` in the Logs folder of your Beat Saber folder).

**Comment by nicoco007** [comment]
Custom Avatars v5.2.8 is now available for Beat Saber 1.17.0 on ModAssistant.
