### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by trunphin** [nicoco007/BeatSaberCustomAvatars#123]
The readme doesn't specify how you use this in Unity.  All the files are in Unity, but they don't do anything.

**Comment by UrkiMimi** [comment]
https://bsmg.wiki/models/avatars-guide.html

**Comment by nicoco007** [comment]
Sorry for not answering earlier, for some reason I completely forgot about this. The guide above is a good starting point and, as explained there, if you have any questions you can ask them in the #pc-3d-modeling channel of the [Beat Saber Modding Group Discord server](https://discord.com/invite/beatsabermods).

Writing a new guide has been something I want to do for quite a while now, I just haven't had the time yet.
