### ISSUE TITLE
Hide in FPFC

### ISSUE THREAD

**Issue by SteffoSpieler** [nicoco007/BeatSaberCustomAvatars#124]
**Is your feature request related to a problem? Please describe.**
Everytime I use fpfc, the leg of my avatar is exactly in the center of the screen and moves with me, so I can't see what I select.

**Describe the solution you'd like**
Maybe somehow detect that fpfc is used and then hide the avatar?

**Describe alternatives you've considered**
Hiding the avatar "in first person" - but I want that in vr.

**Additional context**
![grafik](https://user-images.githubusercontent.com/41108856/147229877-04244445-d998-4f29-a11b-c041c2aaff4f.png)

**Comment by nicoco007** [comment]
Not sure how I missed this. Will definitely get this done for the next release!

**Comment by nicoco007** [comment]
This has been fixed although in a slightly different manner &ndash; the avatar is no longer parented to the FPFC controller so it just stands in the default position instead of flying around with you.
