### ISSUE TITLE
5.2.10 - not showing up in game

### ISSUE THREAD

**Issue by dragonash2019** [nicoco007/BeatSaberCustomAvatars#125]
Noticed you had this updated for 1.19.0, but it will not show any menu or avatars after installation.
I have the latest core mods updated via mod assistant as well.

Not sure what I'm missing

![image](https://user-images.githubusercontent.com/47508016/147249053-03de12e4-a3fe-4dfa-a291-b4c2349d43f4.png)
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/7769606/_latest.log)

**Comment by nicoco007** [comment]
Looks like you don't have DynamicOpenVR installed. You can install it through ModAssistant or download [the latest release](https://github.com/nicoco007/DynamicOpenVR/releases) and install it manually.

**Comment by dragonash2019** [comment]
everything from mod assistant is in there - on top of that, I even downloaded it and installed it manually in case for any reasons, Mod Assistant's was outdated

![image](https://user-images.githubusercontent.com/47508016/147377837-b4725b08-fd85-45f8-89c1-6aad82208d82.png)

**Comment by nicoco007** [comment]
Glad you got it working!
