### ISSUE TITLE
i cant find the custom avatar dll 

### ISSUE THREAD

**Issue by StruckClover588** [nicoco007/BeatSaberCustomAvatars#132]
D :

**Comment by StruckClover588** [comment]
For some readon when i imported in the project there is no custom avatar dll anywhere

**Comment by nicoco007** [comment]
I just looked at [the 5.2.11 zip](https://github.com/nicoco007/BeatSaberCustomAvatars/releases/download/v5.2.11/BeatSaberCustomAvatars-v5.2.11-UnityProject.zip) and it's definitely there, in the `BeatSaberCustomAvatars\Assets\Libraries` folder &ndash; are you sure you extracted everything?

**Comment by nicoco007** [comment]
I'm going to close this since I haven't heard from you in a while. If you're still having trouble, feel free to open a new issue.
