### ISSUE TITLE
Breaks game as soon as installed

### ISSUE THREAD

**Issue by DrTHC** [nicoco007/BeatSaberCustomAvatars#135]
**Before doing anything else, please attach your latest log to this issue. It should be located at `Logs\_latest.log` in your Beat Saber installation's folder.**

LOG: https://pastebin.com/RYp42sk2

**Desktop (please complete the following information):**
- Operating system: Windows 10 - Fully Updated 
- Headset and controllers: Oculus Quest 2 - Airlink with OpenComposite(OpenVR) 

**Describe the bug**
As soon as your mod is installed I either get the game black screen or I get into a menu without any words meaning I cant see what I'm selecting also the colors seem to go a little inverted. 

**Steps to reproduce**
1. Go to Mod Assistant 
2. Add the required mods for custom avatars to work 
3. Load the game up 

**Expected behavior**
The game to work as it should 

**Screenshots**
Screenshot of Bug: https://i.ibb.co/5GdSTZR/Bug.jpg

Edit: Just tried it also with SteamVR and it crashes SteamVR instantly. 
Thanks for checking this out.

**Comment by nicoco007** [comment]
That's very strange. The error seems to be coming from LiteNetLib which isn't something Custom Avatar uses or touches at all... Are you absolutely sure this only happens when Custom Avatars is installed? I honestly don't see how it could be triggering that error.

A few ideas:
- Does it happen if you only have Custom Avatars and its dependencies installed with no other mods?
- Have you tried verifying the integrity of game files and re-installing your mods?

**Comment by DrTHC** [comment]
Hi, I managed to get it working via SteamVR. Would of preferred to use
OpenVR like I was originally as it just works better normally. I'm guessing
it's something to do with how OpenVR handles the headset, which is why it
errors but this was only occuring as soon as your mod was installed. If it
was uninstalled and others where left intact it worked fine but as soon as
avatars was installed it would crash.

**Comment by nicoco007** [comment]
Oh that's interesting. This is a bit of a shot in the dark but could you try adding `--force-xr` when using OpenComposite? I've some some tracking stuff that interacts with SteamVR directly that might be breaking with OpenComposite for some reason.

**Comment by nicoco007** [comment]
Closing this since I haven't heard from you in a while. Feel free to open another issue if you're still having trouble!
