### ISSUE TITLE
Make it work with VMT please.

### ISSUE THREAD

**Issue by LuluViBritannia012** [nicoco007/BeatSaberCustomAvatars#137]
Hey there. First of all, thank you for this incredible mod! It makes Full Body Tracking possible in Beat Saber, with any avatar that we want.

However... I'm using VMT. It didn't work when I tried it, and I see in the latest release of this mod that it's a known bug. Do you know what's the problem exactly? It's weird, because VMT definitely works in SteamVR in my case, I see the "fake trackers" all over my body. It works with VRChat too.

My request is simple : **please find a way to make it work with VMT** ^^.

**Comment by nicoco007** [comment]
I know what's causing the problem, it's just that unfortunately it will take a considerable amount of work to fix it since it revolves around a false assumption I made when creating the tracking system. It's definitely something that'll be fixed but I don't currently have a timeline for it.

**Comment by D3st0ny** [comment]
When? A year has already passed.

**Comment by rickshadow** [comment]
why am i being notified about this email?

**Comment by nicoco007** [comment]
[v5.4.0](https://github.com/nicoco007/BeatSaberCustomAvatars/releases/tag/v5.4.0) now supports VMT as long as you follow [these instructions](https://github.com/nicoco007/BeatSaber-ExtraOpenXRFeatures/tree/main/OpenXRTrackerProfiles#virtualmotiontracker-vmt-additional-setup).
