### ISSUE TITLE
Unity version

### ISSUE THREAD

**Issue by StruckClover588** [nicoco007/BeatSaberCustomAvatars#139]
Where can i find what the current unity version is?

**Comment by StruckClover588** [comment]
Nevermind, i found it. but when it uploads to beatsaber the avatar is in red and saysNullReferenceExeption

**Comment by nicoco007** [comment]
Weird, error messages that pop up there should definitely be more descriptive. Could you send your latest log? It is the file called `_latest.log` in the `Logs` folder of your Beat Saber installation.

**Comment by nicoco007** [comment]
Closing this since I haven't heard from you in a while. Feel free to open another issue if you're still having trouble!
