### ISSUE TITLE
Black box in avatar tab blocking view

### ISSUE THREAD

**Issue by neneko44** [nicoco007/BeatSaberCustomAvatars#14]
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4212134/_latest.log)

I watched a YouTube tutorial on how to get custom avatars and downloaded DynamicOpenVR Version 0.1.1 and BeatSaberCustomAvatars Version 5.0.0 beta 6.1

**Desktop (please complete the following information):**
- Operating system: Windows 10
- Headset and controllers: Oculus Rift S

**Describe the bug**
When I go to the avatar tab, a black box appears blocking off the majority of my screen.

**Screenshots**
![custom avatar black screen](https://user-images.githubusercontent.com/61135858/74629285-ba94e900-510c-11ea-81ae-07a7bba3dc3b.png)

When this happened the first time, I did a fresh install of Beatsaber and used Modassist to put in the preset mods as well as CamerPlus and all mods under "Libraries." It's still happening. ):

Also, when I first boot it up, I think I'm supposed to have a default avatar? But I just see the normal floating sabers with no hands.

**Comment by nicoco007** [comment]
There might be no avatar selected when you first start up with the latest version. As of what I've seen, the black box is rather rare and only shows up when you have "No Avatar" selected; I'm still trying to figure out why. On the right-hand side, you should still be able to select one of the avatars in the list by clicking under the white box you see there. Having an avatar selected should fix the issue temporarily.

**Comment by neneko44** [comment]
Oh thank you! I didn't think to click over there because I haven't seen the menu before. Choosing an avatar is making it work :)
