### ISSUE TITLE
Character it is not displayed

### ISSUE THREAD

**Issue by UtesUrdako** [nicoco007/BeatSaberCustomAvatars#143]
Hello! When selecting a character it is not displayed and on reloading gives the error "Failed no load <name> NullReferenceException: object reference not se to an instance...".
![Screenshot_33](https://user-images.githubusercontent.com/50578504/197376996-8a5e2063-5142-49fa-8b3a-5809248f9fbc.jpg)
![Screenshot_34](https://user-images.githubusercontent.com/50578504/197377026-5b57dc72-753c-4208-a0b0-eeaf6cc0b044.jpg)

**Comment by nicoco007** [comment]
You seem to be running a very old pirated version of the game. I unfortunately do not have the bandwidth to provide help on anything but the latest version. Feel free to open a new issue if you're still having trouble with the latest version of the mod and game.
