### ISSUE TITLE
avatar tracked .25 second desync new gpu

### ISSUE THREAD

**Issue by Benishing** [nicoco007/BeatSaberCustomAvatars#145]
**Desktop (please complete the following information):**
- Operating system:  Windows 10
- Headset and controllers: HTC Vive 

**Describe the bug**
avatar tracking is desynced. happened after gpu upgrade to rx 7900 xtx. delayed by about a quarter of a second.

**Steps to reproduce**
boot game. version 1.27.0 or 1.26.0 test. same results. 

**Expected behavior**
tracking sync to controllers. (controllers track fine)

**Screenshots**
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/10329302/_latest.log)

**Comment by nicoco007** [comment]
This may or may not be related, but NoodleExtensions is throwing an error which in turn causes errors to be thrown every frame. Are you on the latest version? Could you try temporarily uninstalling it to see if that helps?

If the above doesn't help, could you try adding `--force-xr` to the game's Launch Options in Steam?

**Comment by shadowfoxace** [comment]
I am having the same issue on a computer where I recently upgraded to a Radeon 7900xtx as well.  

I'm running on a Valve Index headset. 

Just wanted to let you know I tried both things you suggested, disabling noodle extensions didn't do anything for me but adding the --force-xr argument to the command line resolved the issue. 

Hope this helps

**Comment by Benishing** [comment]
Sorry for the delay had to RMA my 7900 xtx vapor chamber problem. the --force-xr fix my issue.

**Comment by nicoco007** [comment]
Thanks for letting me know. I ended up getting a 7900 XTX of my own and ran into the same issue. It turns out it might be [a bug with SteamVR itself](https://github.com/ValveSoftware/openvr/issues/1729). Until that's figured out, the `--force-xr` launch argument can be used and I'll include an automatic workaround in the next release to avoid further confusion.

**Comment by nicoco007** [comment]
Fixed in version 5.3.2.
