### ISSUE TITLE
Avatar Stays In Default A-Pose

### ISSUE THREAD

**Issue by DiskyNorsk** [nicoco007/BeatSaberCustomAvatars#148]
**Before doing anything else, please attach your latest log to this issue. It should be located at `Logs\_latest.log` in your Beat Saber installation's folder.** [_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/12280771/_latest.log)

**Desktop Info**
- Operating system: Windows 11 Home 22H2
- Oculus Quest 2 (Cabled Link) + Quest 2 Controllers
- Three 3.0 HTC VIVE Trackers + Two 2.0 Base Stations (Making my setup a hybrid)

**Describe the bug**
i'm trying to import an avatar i alrady have out on VRChat working fully but in beat saber after exporting it stays in the default A-Pose and won't follow any of my tracked points (head, both hands, both feet, hip), and i am unaware what i did wrong (also the avatar just glows white because i haven't figured out the Beat Saber Shader yet) but i think it might have something to do with the avatars armature or the fact that the prefab is unpacked

**Steps to reproduce**
1. Import the [PBR Protogen Model](https://twitter.com/triwavebz/status/1514302395836100609?s=20) into Unity
2. Unpack The Prefab
3. Replace PhysBones with Dymanic bones
4. Set unused object's scales to 0, 0, 0 (there are multiple diffrent visors and tails it comes with)
5. Remove Other Unused VRChat assets and scripts
6. Create Avatar Descriptor (and configure)
7. Export
8. Launch Beat Saber and select the avatar

**Expected behavior**
I expected it to just behave like a normal avatar (following tracked points) but instead it's just standing there and glowing

**Screenshots**
[The avatar in question shown in Unity 2019.3.15f1](https://github.com/nicoco007/BeatSaberCustomAvatars/assets/110564749/27fade57-7771-4a1c-b5a1-450f959bc695)
[The same avatar in Beat Saber](https://github.com/nicoco007/BeatSaberCustomAvatars/assets/110564749/1f074f86-4d18-43ff-8e9b-95d51f2948e2)
[How it's expected to behave](https://github.com/nicoco007/BeatSaberCustomAvatars/assets/110564749/8e4f01a2-77af-447a-882e-bd5be957786f)

**Comment by nicoco007** [comment]
I think you're missing the VRIKManager component. Try adding it to the GameObject with your model's Animator (I'm guessing it's on `BZProtoKit` based on your screenshot). It should automatically figure out some defaults if your model already worked with VRChat. If the boxes under "References" are empty, make sure your model is imported using a Humanoid rig, not Generic (or something else) then try again.

As for shaders, you can use one of the built-in ones or the [Uber shader](https://github.com/Ikeiwa/BeatSaber-shaders). Beat Saber uses the alpha channel for glow so most of Unity's shaders won't work out of the box.
