### ISSUE TITLE
Are there any plans for this mod to get a release for versions after 1.29?

### ISSUE THREAD

**Issue by c-x-berger** [nicoco007/BeatSaberCustomAvatars#149]
Title says it all, really. I know the game's Unity version bumped at that point which I imagine is a fairly heavy lift for this mod especially, but I'd love to be able to play new versions with custom avatars (even if I have to remake stuff...)

**Comment by c-x-berger** [comment]
Looks like the answer is "yes, hopefully" from a348ffb. Not sure if avatars must be remade or merely should be remade, I'm not familiar enough with Beat Saber modding to opine on that.

**Comment by nicoco007** [comment]
Yep, I'm still working on this! The only thing big that's left is finishing up [AssetBundleLoadingTools](https://github.com/nicoco007/AssetBundleLoadingTools) which has been delayed a bit by internal discussions to make sure the user experience is decent. Most avatars will still work with the workarounds put in place by that mod but if you have the avatar's source files it's better to re-export with the latest version of Unity to avoid any potential issues.

**Comment by c-x-berger** [comment]
It looks like support for 1.36 happened (959068d457df2eee4e60efd707123030478e742d), but never got tagged/released?

**Comment by nicoco007** [comment]
Just released [v5.4.0](https://github.com/nicoco007/BeatSaberCustomAvatars/releases/tag/v5.4.0) for Beat Saber 1.37.0. I'll be investigating releasing it for 1.34.2 and/or 1.29.1 in the upcoming days.
