### ISSUE TITLE
Avatar stuck in tpose, not responding at all

### ISSUE THREAD

**Issue by Alice67r** [nicoco007/BeatSaberCustomAvatars#15]
as the title says, avatar stuck in tpose and not responding or moving with either full body trackers or the controllers for the htc vive. and yes, I downloading the button mapping for custom avatars. here is my log.
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4302784/_latest.log)

**Comment by nicoco007** [comment]
Looks like you're running a very old version of DynamicOpenVR (0.1.0 beta 3). Could you try installing [the latest version](https://github.com/nicoco007/DynamicOpenVR/releases/tag/v0.1.1) (0.1.1) ? If you're still having issues after that, I'm working on releasing a new version in the next few days that makes DynamicOpenVR optional, which should solve this issue.
