### ISSUE TITLE
AvatarLoadException, Could not load asset bundle.

### ISSUE THREAD

**Issue by TonyHema** [nicoco007/BeatSaberCustomAvatars#151]
**Before doing anything else, please attach your latest log to this issue. It should be located at `Logs\_latest.log` in your Beat Saber installation's folder.**

**Desktop (please complete the following information):**
- Operating system: Windows 11
- Headset and controllers: Oculus Quest 2, Quest 2 Controllers

**Describe the bug**
A clear and concise description of what the bug is. If your issue occurs with a particular avatar, please add a link to where you found it or attach it; **please do not attach the avatar file to this issue if you did not create it**.

**Steps to reproduce**
I have no Idea how to reproduce this error unless this is due to using unity 2022.

**Expected behavior**

**Screenshots**

[2024.01.24.20.27.29.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/14045682/2024.01.24.20.27.29.log)
![image](https://github.com/nicoco007/BeatSaberCustomAvatars/assets/157662099/f19e9b2b-54a2-4655-add4-1e6ffa2da0e5)

**Comment by TonyHema** [comment]
I forgot to state this is BS version 1.29.1

**Comment by nicoco007** [comment]
> I have no Idea how to reproduce this error unless this is due to using unity 2022.

Did you create these avatars? If so, you need to use Unity 2019.4.28f1 or older for Beat Saber 1.29.1. Unity can't load assets exported using a more recent version of the engine; there's nothing I can do about that.

**Comment by TonyHema** [comment]
yeahh figured that out, got it working now tho.

**Comment by nicoco007** [comment]
Great!
