### ISSUE TITLE
1.34.2 support 

### ISSUE THREAD

**Issue by demdos69** [nicoco007/BeatSaberCustomAvatars#152]
when will there be version 1.34.2 support

**Comment by nicoco007** [comment]
Just released [v5.4.0](https://github.com/nicoco007/BeatSaberCustomAvatars/releases/tag/v5.4.0) for Beat Saber 1.37.0. I'll be investigating releasing it for 1.34.2 and/or 1.29.1 in the upcoming days.

**Comment by Joinatic** [comment]
Any Updates for a 1.34.2 release?

**Comment by nicoco007** [comment]
I unfortunately haven't had the motivation to make a release for 1.34.2. I'll close this issue for now but if I ever decide to make such a release, I'll post an update here.
