### ISSUE TITLE
Avatar exporter does not show up due to the "CustomAvatar" not finding "FinalIK"

### ISSUE THREAD

**Issue by SlickierT** [nicoco007/BeatSaberCustomAvatars#155]
Im on a windows 11 working in a project in the version 2019.3.15f1
Im trying to make my avatar playable on beatsaber, however after following various tutorials i still have the same problem of this finalIk not being found( opened and reopened projects, reimported all plugings, retried to do all over again  the tutorials and is still not working)and this issue is making all scripts unusable so i cannot export the avatar.
Is there any way i can solve this issue?
![image](https://github.com/nicoco007/BeatSaberCustomAvatars/assets/149333278/4dc03d9a-e1c4-4f28-990a-48bc97ba8db0)
![image](https://github.com/nicoco007/BeatSaberCustomAvatars/assets/149333278/2ab04227-8c91-4c6b-837e-36483bc8c760)
![image](https://github.com/nicoco007/BeatSaberCustomAvatars/assets/149333278/26ec40f2-eab1-4ac2-adfb-de22d3850af5)
the error in question:
"Error: Could not load signature of CustomAvatar.Utilities.IKHelper:InitializeVRIK due to: Could not load file or assembly 'FinalIK, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:FinalIK, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:<unknown type> member:(null) signature:<none>"
thank you for your patience and sorry if my english is not the best :(

**Comment by nicoco007** [comment]
Hey, sorry about the long wait. You need to copy `FinalIK.dll` and `DynamicBone.dll` as explained in [the avatars guide on the BSMG wiki](https://bsmg.wiki/models/avatars-guide.html#to-unity-and-beyond).

I'd recommend joining [the BSMG Discord server](https://discord.gg/beatsabermods) and asking in the [#pc-3d-modeling](https://discord.com/channels/441805394323439646/468249466865057802) channel in the future. GitHub issues should be reserved for problems with the actual mod, not the avatar creation process.
