### ISSUE TITLE
Building BeatSaberCustomAvatars

### ISSUE THREAD

**Issue by WabsRevenge** [nicoco007/BeatSaberCustomAvatars#156]
Great Work with updating the code to work with the latest version of BeatSaber!

when trying to build, I get nuget failures.

Retrying 'FindPackagesByIdAsync' for source 'https://nuget.pkg.github.com/nicoco007/download/bsipa.assemblypublicizer.msbuild/index.json'.
Response status code does not indicate success: 401 (Unauthorized).

Just wondering if this is by design [i.e. not ready for outside development yet]?

I wanted to try to re-add VRM support, hopefully in a better way than last time so I can create a pull-request at the appropriate time.

**Comment by WabsRevenge** [comment]
worked around it, using package BepInEx.AssemblyPublicizer.MSBuild instead.

managed to get the old VRM code half working. [visible in just one-eye counts as half, right?]

**Comment by nicoco007** [comment]
I use GitHub Packages so you just need to add your authentication information. Visual Studio and Rider should automatically prompt you, or you can add it through the .NET CLI [in the same way as CI](https://github.com/nicoco007/BeatSaberCustomAvatars/blob/main/.github/workflows/build.yml#L28) with your username and a classic personal access token with the `read:packages` permission.
