### ISSUE TITLE
Doesn't appear to start up

### ISSUE THREAD

**Issue by Vesperindustrial** [nicoco007/BeatSaberCustomAvatars#157]
[_latest.log](https://github.com/user-attachments/files/15859908/_latest.log)

**Desktop (please complete the following information):**
- Operating system: Windows 10
- Headset and controllers: HP Reverb G2
- Beat saber 1.37.0

**Describe the bug**
Beat saber does not appear to start up. I only got it to get to the main menu maybe once out of 10+ attempts. It will show the beat saber logo for a split second but then the window will lock up and not recover. SteamVR will also seemingly quit as well when this happens. I'm not sure if this is due to assetbundleloadingtools needing an update as it says on the release page it only supports up to 1.35?

**Comment by WabsRevenge** [comment]
I found something similar when adding customavatars to an old and updated installation. I found uninstalling beatsaber and reinstalling and re-adding the mods helped.

**Comment by Vesperindustrial** [comment]
Unfortunately i tried 3 different times and the result was still the same :(

**Comment by Vesperindustrial** [comment]
Ok I appear to have finally fixed it, you actually have to tell steam to use steamVR as the openXR runtime, previously the base system would (and WMR still does) complain that its not the primary openXR runtime, but it appears to not matter now where it did before. So this would probably apply to anyone else using a WMR headset. I should note that if you dont use any of the optional items in the pre-requisite list it also seems to work fine even without switching it to steamVR.
