### ISSUE TITLE
Pico Motion Tracker not working

### ISSUE THREAD

**Issue by Cassadin** [nicoco007/BeatSaberCustomAvatars#158]
- Operating system: Windows 11
- Headset and controllers: Pico 4 + Pico Motion Tracker

After fully setting up the VMT ... i can not picker a profile named vtm* like shown here
![image](https://github.com/user-attachments/assets/c8ea9937-8586-479c-8fe5-418afae31328)

due to that ... the game tells, that there are no trackers assigned.

Since i dont have 1800€ for 10000 vive trackers ... i would to use the trackers, which i have ... they are compatible with other games.

**Comment by nicoco007** [comment]
Did you [set up tracker roles in SteamVR](https://github.com/nicoco007/BeatSaber-ExtraOpenXRFeatures/tree/main/OpenXRTrackerProfiles#assigning-steamvr-tracker-roles)? The vmt_* entries should show up once you've done that. If they don't, it's either an issue with your setup or with VMT itself and there's not much I can do to help. You can check [VMT's documentation](https://gpsnmeajp.github.io/VirtualMotionTrackerDocument/) for configuration/troubleshooting.

**Comment by Cassadin** [comment]
> Did you [set up tracker roles in SteamVR](https://github.com/nicoco007/BeatSaber-ExtraOpenXRFeatures/tree/main/OpenXRTrackerProfiles#assigning-steamvr-tracker-roles)? The vmt_* entries should show up once you've done that. If they don't, it's either an issue with your setup or with VMT itself and there's not much I can do to help. You can check [VMT's documentation](https://gpsnmeajp.github.io/VirtualMotionTrackerDocument/) for configuration/troubleshooting.

Yes, I did. Every Pico tracker has assigned their body part and every other entry is set do deactivated.
Still, in the configuration UI I only have configurations for controller and not for tracker.
Tried that with game started and without game started.

**Comment by nicoco007** [comment]
Have you tried doing this while your trackers are turned on and connected? I just checked on my end and it looks like the vmt_* options only show up once SteamVR shows the VMT trackers as connected.

**Comment by nicoco007** [comment]
I'll be closing this issue within the next few days if I don't hear back.

**Comment by Cassadin** [comment]
> Have you tried doing this while your trackers are turned on and connected? I just checked on my end and it looks like the vmt_* options only show up once SteamVR shows the VMT trackers as connected.

The Pico Tracker itself were turned on.
steam showd them green ... and the VMT were shown blue.

**Comment by nicoco007** [comment]
Unfortunately there's nothing I can do to help. The instructions I wrote are essentially the same as [VMT's own instructions](https://gpsnmeajp.github.io/VirtualMotionTrackerDocument/advanced/) with adjustments for OpenXR. The only thing I can recommend at this point is reinstalling SteamVR and/or VMT and make sure you're running the latest versions of both.
