### ISSUE TITLE
Pino Soft motion tracker not working

### ISSUE THREAD

**Issue by Azshurith** [nicoco007/BeatSaberCustomAvatars#160]
I bought the full version of the pinosoft application and it seems it does not track both foot.
I already did bind them correctly.

VMT Version: VMT_015
Beat Saber Version: 1.37.1
Custom Avatar Version: 5.4.1
Device: iPhone 15
FBT Application: Pinosoft / PinoFBT

![image](https://github.com/user-attachments/assets/4bf81d1f-9af2-4c6c-a6fb-7610251703f3)

![image](https://github.com/user-attachments/assets/ddf1c1b1-fb89-4823-83c6-42505e2878d5)

![image](https://github.com/user-attachments/assets/62eb5efb-bd85-42e9-9d5f-bc01af6496c6)

![image](https://github.com/user-attachments/assets/ea3f7375-4eab-454c-8a3f-106ce232fd1c)

**Comment by fchen09** [comment]
https://youtu.be/HM6AbUg_GKM/
binding tutorial

**Comment by nicoco007** [comment]
Just to clarify, you can see them tracking when the SteamVR dashboard is open, correct? In the Avatars menu, do you see a message that says _Tracker support is not available. Please install OpenXRTrackerProfiles._ or _No trackers detected. Did you assign roles to your trackers in SteamVR?_ If you go to the _Current Avatar_ tab, does anything happen if you choose _
