### ISSUE TITLE
Avatars are wrong

### ISSUE THREAD

**Issue by Terrabytes13** [nicoco007/BeatSaberCustomAvatars#164]
**Before doing anything else, please attach your latest log to this issue. It should be located at `Logs\_latest.log` in your Beat Saber installation's folder.**

**Desktop (please complete the following information):**
- Operating system: Windows 11
- Headset and controllers: HTC Vive

**Describe the bug**
Whenever i load some of the avatars, theyre in a crab-like position. I've installed all necessary plugins as listed and did a trial between 1.29.1 and 1.37.3.... theyre fine when i loaded in 1.29.1 but broken in 1.37.3. I get the mod isnt 'officially' available yet too 

**Steps to reproduce**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**
not sure how to do this in game

**Comment by nicoco007** [comment]
Could you please share the avatar(s) that have this problem?

**Comment by Terrabytes13** [comment]
Chocola https://modelsaber.com/Avatars/?id=1622158752&7pc

Vanilla https://modelsaber.com/A<https://modelsaber.com/Avatars/?id=1622158719&pc>v<https://modelsaber.com/Avatars/?id=1622158719&pc>atars/?id=1622158719&pc<https://modelsaber.com/Avatars/?id=1622158719&pc>

Miku V3 https://modelsaber.com/Avatars/?id=1622158637&pc

Miku V4 https://modelsaber.com/Avatars/?id=1620882608&pc

These are some that I've loaded in and they all appear like this, as crab like, yet in the version prior (1.29.1) to updating to 1.37.3 they broke.
Surprisingly enough there's a Miku V3 of another one that works fine.
________________________________

**Comment by nicoco007** [comment]
Thanks! I found the issue. It'll be fixed in the next release!

**Comment by nicoco007** [comment]
Fixed in [version 5.4.5](https://github.com/nicoco007/BeatSaberCustomAvatars/releases/tag/v5.4.5).
