### ISSUE TITLE
Pico Motion Trackers are not detected

### ISSUE THREAD

**Issue by k3lwin** [nicoco007/BeatSaberCustomAvatars#168]
Hi!

I am trying to make use of 2nd gen Pico Motion Trackers (the round ones) to add locomotion to my avatar. As far as I understand, Pico Connect software does not simply bypass data from trackers to SteamVR, instead it does its own bone approximation and then populates device tree with a bunch of virtual trackers. Anyway, the plugin doesn't seem to detect any of them, and I'm at my wit's end about how should I debug it further.

Every virtual tracker is mapped in SteamVR. I tried disabling every tracker except for ankle trackers and map them to ankles, still no luck.

I tried it on BS 1.37.1 with CustomAvatars 5.4.1+bs.1.37.0, OpenXRFeatureManager@1.0.1 and OpenXRTrackerProfiles@1.0.0, but the issue seems to be present in 1.38.0 with CustomAvatars 5.4.6 as well.

These trackers are fairly new and Pico implemented SteamVR support for them not that long ago, so I understand if CustomAvatars does not have support for them yet. I'm ready to test new releases and to provide more debug info if needed.

- Operating system: Windows 11 23H2
- Headset and controllers: Pico 4 with stock Phoenix controllers, 2x Pico Motion Trackers

![Screenshot_com picovr picostreamassistant_2024 10 20-16 54 58 318_621](https://github.com/user-attachments/assets/849d44e5-7b1c-45d3-a97d-749777ca7119)
![Screenshot_com picovr picostreamassistant_2024 10 20-16 32 35 519_112](https://github.com/user-attachments/assets/6ba7421d-fb42-4688-a03e-e7ba76b953be)
![Screenshot_com picovr picostreamassistant_2024 10 20-16 33 11 567_402](https://github.com/user-attachments/assets/8f900219-c3e1-45ab-a5be-e5bb796a7bf0)
![Screenshot_com picovr picostreamassistant_2024 10 20-16 35 49 587_877](https://github.com/user-attachments/assets/1b513bb7-8d3c-4492-8451-dc1e32068866)

[_latest.log](https://github.com/user-attachments/files/17450428/_latest.log)

**Comment by nicoco007** [comment]
I'm seeing a few errors in your log that aren't directly related to trackers but might be indirectly impacting them. Could you try [this build](https://github.com/user-attachments/files/17451195/CustomAvatar-v5.4.7%2Bbs.1.37.4.git.sha.3a33d82d6b6184d590ee7a666fc81c5e0e58f4a9.zip) (for 1.37.4 &ndash; 1.38.0) out and see if it helps? If it doesn't, could you post the log it produces?

Also, if you follow the [VMT instructions](https://github.com/nicoco007/BeatSaber-ExtraOpenXRFeatures/tree/main/OpenXRTrackerProfiles#readme) up until step 9, do you see anything tracker-related in the list **when your trackers are turned on and connected**? You won't see the `vmt_*` entries but are there entries in addition to the controller ones? For example, after I've turned on my Vive trackers, they show up in the list:
![image](https://github.com/user-attachments/assets/c68afcd7-b875-4637-85a1-875c2b599a5f)

**Comment by k3lwin** [comment]
Tested this build on a fresh 1.38.0 instance - no dice, trackers are still not detected. [_latest_1.38.0.log](https://github.com/user-attachments/files/17451334/_latest_1.38.0.log)

There are no entries for trackers in controllers list of binding UI, even though tracking clearly works. This might be the issue right there.
![Screenshot_com picovr picostreamassistant_2024 10 20-20 00 32 959_631](https://github.com/user-attachments/assets/1e815b78-7712-4a00-aba0-3849478c9d2b)

**Comment by nicoco007** [comment]
Yeah, my guess is that they haven't fully implemented things on the SteamVR Input side of things yet. Have you tried following [these instructions](https://github.com/Elbios/pico-motion-trackers-steamvr-guide) by any chance? They go through adding profiles for the trackers (which is what my VMT instructions are doing) but manually with files rather than through the SteamVR UI.

**Comment by k3lwin** [comment]
That worked, thank you so much!

To sum up, here's what I did to solve this:
- Followed the [guide you provided](https://github.com/Elbios/pico-motion-trackers-steamvr-guide) up until step 5.
- Launched SteamVR and disabled all Pico trackers except for ankles:
![Screenshot_com picovr picostreamassistant_2024 10 20-20 54 48 891_032](https://github.com/user-attachments/assets/e032b78c-6e82-43c9-a33f-6403bd98cb73)
- Mapped Pico trackers for feet with corresponding feet (even though Pico tracker configuration page says ankles):
![Screenshot_com picovr picostreamassistant_2024 10 20-20 54 39 369_038](https://github.com/user-attachments/assets/3a27a0c1-d9b4-4f70-9941-1e27ebac8f65)
- Launched Beat Saber and manually calibrated trackers.

This worked on older Beat Saber 1.37.1 with Custom Avatars 5.4.1. Hope this helps!
