### ISSUE TITLE
No trackers found

### ISSUE THREAD

**Issue by JaroslawPokropinski** [nicoco007/BeatSaberCustomAvatars#169]
**Before doing anything else, please attach your latest log to this issue. It should be located at `Logs\_latest.log` in your Beat Saber installation's folder.**

**Desktop (please complete the following information):**
- Operating system: Windows 11
- Headset and controllers: Quest 2 + Slime VR

**Describe the bug**
Trackers are not detected by the game, they work correctly in the VR Chat.

**Steps to reproduce**
Connect trackers, connect to the game (i used both steam link and oculus link with steam VR, steam VR is set as the default OpenXR runtime).

**Expected behavior**
Trackers should be detected

**Screenshots**
![Screenshot 2024-11-10 173453](https://github.com/user-attachments/assets/b89541bf-4114-4185-ab03-d1955b81b99e)
![Screenshot 2024-11-10 173519](https://github.com/user-attachments/assets/2d445b85-5f52-4018-89cb-cd267db6fcc2)
![Screenshot 2024-11-10 173513](https://github.com/user-attachments/assets/0977a628-3c33-4f0d-8f96-c8f37d73ac22)

**Logs**

[_latest.log](https://github.com/user-attachments/files/17692213/_latest.log)

**Comment by nicoco007** [comment]
As the message says, please make sure you've installed OpenXR Tracker Profiles properly. It is available through mod managers or you can [download and install it manually](https://github.com/nicoco007/BeatSaber-ExtraOpenXRFeatures/releases).

**Comment by JaroslawPokropinski** [comment]
My bad, I assumed it meant to set it in the steam assignments. I thought I followed the instructions but I missed this part (the link in the read me jumps to Assigning SteamVR Tracker Roles section just below the put dll part). After installing the mod in mod assistant all is fine. Thanks for your help :)

**Comment by nicoco007** [comment]
Glad you got it working! I'll see if I can make that clearer in the instructions.
