### ISSUE TITLE
Avatar Height not Matching Player Height

### ISSUE THREAD

**Issue by alexankitty** [nicoco007/BeatSaberCustomAvatars#17]
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4363224/_latest.log)

**Desktop (please complete the following information):**
- Operating system: Windows 10 1903
- Headset and controllers: Valve Index

**Describe the bug**
When visible in first person is enabled, using either automatic height or manually setting height in beat saber results in being able to see your head in first person as the avatars head is physically lower than the HMD. This also results in the avatars knees being slightly bent as if they're crouching. This can be worked around by forcing beat saber to register a height 0.1m higher than your own. It's also worth noting that the issue goes away when switching avatars, but if beat saber is set to automatic height or manually to your correct height the issue will reappear when you click play on a song.

**Steps to reproduce**
1. Set player height to automatic or manually set it when standing up straight
2. Select an avatar (Optionally enable first person view to see the effect easier)
3. Set resize to height.
3. Go into a song and click play.
4. Look down while you do this and you should see inside your head (this has happened with multiple avatars)
5. Exit and go into the avatar menu, the avatar's legs will also be slightly bent as if in a crouch.

**Expected behavior**
When looking around you should never be able to see the avatar's head (provided the avatar has the necessary culling for this.) The avatar's height should also match the player's height when set to resize on height, however currently seems to be .1m higher.

**Screenshots**
Avatar after resetting by loading a new one
![20200321101817_1](https://user-images.githubusercontent.com/45508320/77231079-36e07900-6b5e-11ea-9c3e-9138ffab081c.jpg)

Custom Avatar Settings (Fix Floor does not have any effect on this issue)
![20200321101820_1](https://user-images.githubusercontent.com/45508320/77231029-e9640c00-6b5d-11ea-9225-3cb40d5260a2.jpg)

Beat Saber in game height settings
![20200321101841_1](https://user-images.githubusercontent.com/45508320/77231040-f680fb00-6b5d-11ea-8a3c-4c168fbc41f3.jpg)

Clicking the play button while looking down, avatar is not visible
![20200321101828_1](https://user-images.githubusercontent.com/45508320/77231044-00a2f980-6b5e-11ea-933b-7331c1927d5f.jpg)

Avatar is visible once the play button has been clicked
![20200321101853_1](https://user-images.githubusercontent.com/45508320/77231047-0a2c6180-6b5e-11ea-8259-bc2cbaf5b527.jpg)

A slight bend can be seen in the avatar as well indicating that avatar height isn't matching player's height
![20200321101910_1](https://user-images.githubusercontent.com/45508320/77231052-144e6000-6b5e-11ea-9948-d1869d3a851c.jpg)

**Comment by nicoco007** [comment]
Thanks for the detailed bug report! Turns out this is caused by the same underlying issue that was causing #5.

Could you try these builds and let me know if that fixes it?
* [Custom Avatars](https://ci.gnyra.com/job/BeatSaberCustomAvatars/job/develop/98/artifact/BeatSaberCustomAvatars-d7f5bc4-RELEASE.zip)
* [DynamicOpenVR](https://ci.gnyra.com/job/DynamicOpenVR/job/master/132/artifact/DynamicOpenVR-5fd09c6-RELEASE.zip)
* [DynamicOpenVR.BeatSaber](https://ci.gnyra.com/job/DynamicOpenVR/job/master/132/artifact/DynamicOpenVR.BeatSaber-5fd09c6-RELEASE.zip)

**Comment by alexankitty** [comment]
I can confirm that fixed it.

**Comment by nicoco007** [comment]
Great! This'll be included in the next release.

**Comment by alexankitty** [comment]
Sounds good! Thanks so much for looking into this! :)
