### ISSUE TITLE
Cannot find Avatar option under Mods Tab

### ISSUE THREAD

**Issue by lixonhlx** [nicoco007/BeatSaberCustomAvatars#18]
Hi, 

I have DynamicOpenVR and Custom Avatar folders copied into Beat Saber's installation folder, but I could not find the custom avatar option under the mod tab.

- Operating system: Windows 10
- Headset and controllers: Samsung Odyssey Plus
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4396480/_latest.log)

**Comment by nicoco007** [comment]
Looks like you're using an old version of DynamicOpenVR that isn't compatible with Beat Saber 1.8.0. Could you try downloading and installing [the latest version](https://github.com/nicoco007/DynamicOpenVR/releases/tag/v0.2.0)?

**Comment by lixonhlx** [comment]
Hi, I missed the latest version on the top of the page...Everything is good now! Thank you so much!
