### ISSUE TITLE
Latest version fails to properly set an initial avatar and therefore fails to load any

### ISSUE THREAD

**Issue by hedonicknight** [nicoco007/BeatSaberCustomAvatars#19]
**Describe the bug**
The latest version of this plugin tries to use 'default settings' which, even in verbose mode, fails to show what path it's trying to reach. Therefore, using Pg Up/Pg Dn only results in NullReferenceExceptions to be thrown, saying there's no instance of the object (I imagine this is the index failing to be set).

**Steps to reproduce**
1. On install, keep ALL default settings.
2. Do NOT set a UserData/CustomAvatars.json file.
3. Start the game.

**Workaround**
1. After install, create UserData/CustomAvatars.json as a new file.
2. Create an entry: `{
     "previousAvatarPath": "<any of your avatar files name>.avatar"
}`
3. Model properly loads. Page up/dn properly work again.

**Comment by hedonicknight** [comment]
I didn't include my latest log because my workaround fixed the issue, and therefore made my latest log a 'working' version.

**Comment by nicoco007** [comment]
Good catch! I'm able to reproduce it on my end; this'll be fixed in the next release.

**Comment by nicoco007** [comment]
Beta 8 was just released and should fix this issue. If you are still having problems, feel free to reopen this issue or create a new one.
