### ISSUE TITLE
Some avatar will render with the wrong height for other players when using the Multiplayer Mod

### ISSUE THREAD

**Issue by HugKitten** [nicoco007/BeatSaberCustomAvatars#23]
**Desktop (please complete the following information):**
- Operating system: Windows 10
- Headset and controllers: Oculus Rift s

**Describe the bug**
Some avatars (I was using the "Ooka Miko 2nd Form" avatar and he was using the "Meika Mikoto" avatar) will show properly for the person wearing the avatar, but will display the avatar without the adjusted size to other players. I noticed this when me and my friend and we couldn't see each other correctly. When I pat his head, he would see my hands in his face. When he tries to head pat me, his hands are always below my avatar's height, but wouldn't be in my face. I'm about 5"7 and hes 5"11. Also his avatar has a greater size difference than his height which probably makes it more noticeable on his end. Once we switched to another avatar "Ooka Miko" we found that the height of the avatar was rendered correctly for each other and I saw on his screen what he saw on my screen. (We have the camera plus mod) This may be an issue multiplayer mod itself.

**Steps to reproduce**
1. Set up the multiplayer mod with the mod installer on its read me (and all its required dependencies and such) Use BSIPA version 4.0.3. The installer will include the avatar mod. (Version 5.0.0 beta 7 I believe)
2. Pick one of the broken avatars ("Ooka Miko 2nd Form" or "Meika Mikoto"). 
3. Enable the option to resize the avatar to your height or arm length.
4. Go into a room with people and ask them where your avatar's head is.
5. Notice that their hands are usually below your actual avatar's height.

**Expected behavior**
That avatars would display with the correct height

**Screenshots**
Forgot to take any.

**Avatars**
[avatars.zip](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4463096/avatars.zip)

**Comment by nicoco007** [comment]
Thanks for the detailed report! If it's only the other players' avatars that aren't being resized properly, then it's most likely an issue on the multiplayer mod's end. I also noticed that they're asking users to install a non-official build of CustomAvatars [in the repo's readme](https://github.com/andruzzzhka/BeatSaberMultiplayer/blob/master/README.md); I'm going to have to ask the author why that's the case and see if any changes that were made there can be integrated into the mod.

**Comment by HugKitten** [comment]
Alright! Thanks for taking the time to read over the report and everything. I know this issue was likely on the mod author.

**Comment by HugKitten** [comment]
I think the issue may be fixed by having the multiplayer mod send avatar scale and use that for the size instead of the way it's currently doing it. It'd also ensure that players looked the same to each other no matter what setting they have on the avatar mod. That being said, I don't really know a whole lot about unity or how it handles VR.

**Comment by nicoco007** [comment]
I'm going to close this for now since I'm 99% sure this is an issue on Multiplayer's end, but feel free to reopen it if turns out it isn't.
