### ISSUE TITLE
Custom Avatar Exporter is broken with new CustomAvatar.dll

### ISSUE THREAD

**Issue by ellisgeek** [nicoco007/BeatSaberCustomAvatars#25]
**Before doing anything else, please attach your latest log to this issue. It should be located at `Logs\_latest.log` in your Beat Saber installation's folder.**
Not Applicable

**Desktop (please complete the following information):**
- Operating system: Windows 10
- Headset and controllers: Oculus Rift CV1

**Describe the bug**
When Importing the new CustomAvatar.dll into unity the AvatarExporterWindow.cs script breaks because AvatarDescriptor.Name and AvatarDescriptor.Author have been changed to lowercase.

**Steps to reproduce**
Import the new CustomAvatar.dll into an existing Unity Project.

Gist with Fixed editor script:
https://gist.github.com/ellisgeek/5ecec00e536aa38dcf0d800c68ad434c

**Comment by nicoco007** [comment]
Yeah, this is a known issue. It has already been addressed in #22.
