### ISSUE TITLE
When i put sabers close to my face they disappear

### ISSUE THREAD

**Issue by Crafty-The-Fox** [nicoco007/BeatSaberCustomAvatars#3]
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/3996312/_latest.log)

I am on Windows 10, using a oculus rift CV1, when ever i put the sabers close to my face, they disappear

**Comment by nicoco007** [comment]
Could you try following the instructions under [Sabers/hands disappear when brought up to the face](https://github.com/nicoco007/DynamicOpenVR/blob/master/TROUBLESHOOTING.md#2-sabershands-disappear-when-brought-up-to-the-face)?

**Comment by nicoco007** [comment]
Closed due to inactivity. Feel free to reopen if you're still having this issue.
