### ISSUE TITLE
Question: How to use new editor DLLs?

### ISSUE THREAD

**Issue by Interpause** [nicoco007/BeatSaberCustomAvatars#30]
Using BeatSaberCustomAvatars-v5.0.0-beta.7-Editor.zip, I directly replaced the existing CustomAvatar.dll, DynamicBone.dll and FinalIK.dll in the Assets folder of the editor package downloaded from https://bs.assistant.moe/Avatars/. 

After doing so, I get these errors. The last error occurs upon attempting to open the exporter.
![image](https://user-images.githubusercontent.com/42513874/81079057-9d103800-8f21-11ea-9034-1bd424004ea6.png)

Judging from the error, it seems to be a possible bug in the declaration of AvatarDescriptor in the new DLL as well as an error in the versioning (which would probably be the fault of a yet un-found manifest file or something).

More likely, it is because directly replacing the DLLs is not the correct method of installing the editor update. As such, could I ask what is the correct method for doing so please?

**Comment by Interpause** [comment]
After looking through the source code I believe the error is due to a change in capitalization of "Author" to "author" and "Name" to "name" in the master version. Shall now attempt to compile a new version of the editor package using the master branch to see if it persists.

**Comment by Interpause** [comment]
Avatar exported has resulted in the game being able to proceed past the disclaimers. Will be reverting to old editor for now to export avatar...

**Comment by kanauru** [comment]
I ran into issues too and I believe this quick fix solves it 
https://github.com/ErrorUser-not-found/BeatSaberCustomAvatars/releases

I actually used another DLL someone uploaded on the discord which solved the problem
[https://cdn.discordapp.com/attachments/468249466865057802/698123700536344686/CustomAvatar.dll](url)

I'm not sure if both are the same thing but the latter one definitely worked for me.

**Comment by nicoco007** [comment]
Unfortunately, that guide is incredibly outdated; I'll be writing a new one eventually. I would rather you avoid using non-official builds because they will most likely not be kept up-to-date and may cause issues in the future. Instead, please see [the comment I left here](https://github.com/nicoco007/BeatSaberCustomAvatars/issues/22#issuecomment-612212048) to get it working.

`IKManager` and `IKManagerAdvanced` have been removed from the editor DLL because they should no longer be used. Please use `VRIKManager` instead.

**Comment by Interpause** [comment]
> I ran into issues too and I believe this quick fix solves it
> https://github.com/ErrorUser-not-found/BeatSaberCustomAvatars/releases
> 
> I actually used another DLL someone uploaded on the discord which solved the problem
> [https://cdn.discordapp.com/attachments/468249466865057802/698123700536344686/CustomAvatar.dll](url)
> 
> I'm not sure if both are the same thing but the latter one definitely worked for me.

Ah thanks it worked (when not using both of them at the same time.. I guess one adds back the capitalization and the other removes it whoops). 
Also for anyone who comes across this issue, it seems that you only need to attach VRIK Manager without needing VRIK. Took a few attempts debugging why full body tracking wasn't working properly to figure that out.
