### ISSUE TITLE
Full Body Avatar Template?

### ISSUE THREAD

**Issue by kanauru** [nicoco007/BeatSaberCustomAvatars#31]
The 'Full Body Avatar' that comes default works great.

I've been having with trouble with getting my avatar to track just as well.

Is there a unity project available for the full body avatar so I can compare and use a reference.

Thanks!

**Comment by nicoco007** [comment]
I'll be releasing a new Unity project with all the new stuff including the reworked Full Body Template avatar alongside the next release of Custom Avatars, which should *hopefully* happen within the next week or two.

**Comment by kanauru** [comment]
Awesome. Thanks! 
Looking forward to the VRchat like calibration too whenever that is out.

**Comment by zenmetsu** [comment]
I am looking forward to this release as well.  For whatever reason, in following the tutorials online, the avatar keeps mixing up Pelvis and Left leg.  Right leg works fine, but no matter what I do, pelvis and left leg end up getting swapped.

**Comment by kanauru** [comment]
> I am looking forward to this release as well. For whatever reason, in following the tutorials online, the avatar keeps mixing up Pelvis and Left leg. Right leg works fine, but no matter what I do, pelvis and left leg end up getting swapped.

If things are swapped it's most likely because you didn't turn on your trackers in the right order . Basically turn on left feet, right feet, then pelvis tracker last. Otherwise I'm not sure what's wrong.

**Comment by zenmetsu** [comment]
> 
> 
> > I am looking forward to this release as well. For whatever reason, in following the tutorials online, the avatar keeps mixing up Pelvis and Left leg. Right leg works fine, but no matter what I do, pelvis and left leg end up getting swapped.
> 
> If things are swapped it's most likely because you didn't turn on your trackers in the right order . Basically turn on left feet, right feet, then pelvis tracker last. Otherwise I'm not sure what's wrong.

You are right, i'm a retard.  The fact that the order matters is incredibly counterintuitive given that SteamVR has assignments for each tracker.  :/

**Comment by nicoco007** [comment]
Custom Avatars actually takes the tracker roles into account, I just accidentally broke it in beta 7. It'll be fixed in the next release.

**Comment by KAAquilla** [comment]
When loading in the new CustomAvatar.dll in the Unity project I just get this error spewing in the console when I select the asset.
Am I missing something?
![grafik](https://user-images.githubusercontent.com/18380794/88321987-5233de80-cd20-11ea-8fea-8c0a9856880e.png)

**Comment by nicoco007** [comment]
What version of Unity are you using? Beat Saber is now on 2019.3.2f1 so try switching to that if you haven't already (make sure you have a backup of your project just in case).

**Comment by nicoco007** [comment]
Sorry for taking so long. A new Unity project is included with the release of version 5.0.0. It's a bit barebones but it contains the avatar files for both the "Template" and "Template - Full Body" avatars.
