### ISSUE TITLE
3rd person camera? Am I missing something?

### ISSUE THREAD

**Issue by JohnyDL** [nicoco007/BeatSaberCustomAvatars#32]
No Logs

Win10 Vive Cosmos Elite

**Describe the bug**
I cant see the avatar at all using the third-person camera (or smooth camera) although the mirror of the avatar does show up for the third person camera.

**Steps to reproduce**
Install Custom Avatars and DynamicOpenVR for most recent version (1.9.1 I think) of Beat Saber 
Try on an avatar but nothing displays on the computer monitor as though I'm inhabiting it

**Expected behavior**
Avatar displays for third person mode even if hidden from first person mode so that it can be recorded/streamed

No Screen shots at this time (it's late and I didn't think to do that)

I'm guessing there's some obvious step I've missed to make the Avatar appear for third person/smooth camera rather than this being a bug but I didn't spot any obvious thing to make it work or that anyone else had asked this question

**Comment by fuyushi** [comment]
for cameraPlus make sure the show avatar is toggled on. it's one of the options when you rightclick on the game window on your PC

**Comment by JohnyDL** [comment]
okay I went down a rabbit hole and got cameraplus set up too thanks, I thought all I'd need was smooth camera unlimiter and the default desktop view. All fixed now

**Comment by nicoco007** [comment]
I'm happy you were able to get it working with CameraPlus. I wasn't aware of SmoothCameraUnlimiter, so I'll still try and see if this can be fixed.
