### ISSUE TITLE
request: expose "moveFloorWithRoomAdjust"

### ISSUE THREAD

**Issue by fuyushi** [nicoco007/BeatSaberCustomAvatars#33]
I imagine at least some players use room adjust to like say 0.05 Y to play at their prefered height. 
Under default settings that will cause the avatar to slightly crouch at all times. This can be solved by setting  "moveFloorWithRoomAdjust" to true in the config file, which is however not exposed in the ingame UI and because of that hard to even know it's even an option.

**Comment by nicoco007** [comment]
This should be pretty trivial to implement so I'll try to include it in the next release.

**Comment by nicoco007** [comment]
This has been added in beta 8, which was just released.
