### ISSUE TITLE
request: platform mirror functionality

### ISSUE THREAD

**Issue by fuyushi** [nicoco007/BeatSaberCustomAvatars#34]
Right now when the mirror quality is enabled (low or high) the model will be reflected on the stages standing platform if 'Visible in first person' is also enabled. However, only mesh that isn't hidden by the first person exclusion script will be reflected. 
 I don't know if this is possible technically, but it would be nice if either: 
- even first person excluded mesh would still be reflected 
- or have it generally reflected, even if 'visible in first person' is off

**Comment by nicoco007** [comment]
Just checked and it is definitely possible! This'll be included in the next release.

**Comment by nicoco007** [comment]
This has been added in beta 8, which was just released.
