### ISSUE TITLE
Bug full body tracking (kinecttovr and driver4vr)

### ISSUE THREAD

**Issue by MirkoMirror** [nicoco007/BeatSaberCustomAvatars#4]
it's really scary xD, any avatar has the body and legs turned backwards
I used Windows mixed reality headset and KinectToVr
(with driver4vr the problem persists)

**Comment by nicoco007** [comment]
Yeah I've had another report of this being an issue. I'm unfortunately away from home right now and don't have my Kinect with me so I probably won't be able to work on this until at least next week, but I'll try to get a fix out ASAP.

**Comment by MirkoMirror** [comment]
thank you so much for your work

Il Ven 27 Dic 2019, 20:00 Nicolas Gnyra <notifications@github.com> ha
scritto:

**Comment by nanit568** [comment]
Dear Nicoco.
I'm facing an issue with driver4vr. Legs are not moving as expected. Is the issue with driver4vr (which was in Version 5.0.0 beta 5) fixed in latest version?

**Comment by TsukikoChan** [comment]
> Dear Nicoco.
> I'm facing an issue with driver4vr. Legs are not moving as expected. Is the issue with driver4vr (which was in Version 5.0.0 beta 5) fixed in latest version?

I am in the same boat, driver4VR does not work at v5.0.0 beta6.1. Have you had any luck with your Kinect Nicoco? Thank you for the hard work <3

**Comment by TsukikoChan** [comment]
> Dear Nicoco.
> I'm facing an issue with driver4vr. Legs are not moving as expected. Is the issue with driver4vr (which was in Version 5.0.0 beta 5) fixed in latest version?

I am in the same boat, driver4VR does not work at v5.0.0 beta6.1. Have you had any luck with your Kinect @nicoco007 ? Thank you for the hard work <3

**Comment by simba-limba** [comment]
When will this issue be
 fixed?

**Comment by nicoco007** [comment]
I am off for most of this upcoming week so I should be able to get to it in the next few days. Sorry this is taking so long!

**Comment by nanit568** [comment]
Hi @nicoco007 .
No worries. Thank you for your time and job!

**Comment by TsukikoChan** [comment]
Agreed with @nanit568 , thank you for taking your time so for us and this project  @nicoco007 !

**Comment by simba-limba** [comment]
Take your time mate

**Comment by TsukikoChan** [comment]
I dunno if it helps but driver4vr released a new driver version the other day, it might make things a lil easier maybe? :-)

**Comment by nicoco007** [comment]
I believe f4f2351 and 6d58c84 have fixed most of the issues and will be included in the next release. You can try it out in [this build](https://ci.gnyra.com/job/BeatSaberCustomAvatars/job/develop/96/artifact/BeatSaberCustomAvatars-6d58c84-RELEASE.zip) (though other stuff might be broken).

**Comment by TsukikoChan** [comment]
Thanks, I'll give that a wee whirl this weekend at some point. How do we backtrack if we want to go back to a stable release (until the next revision releases)? just extract 6.1 straight over?

**Comment by nicoco007** [comment]
Yep!

**Comment by TsukikoChan** [comment]
I tried it over the weekend Nico, extracting the files into the beatsaber folder and the mod no longer shows up in BeatSaber so i couldn't properly test. Is there missing pre-requisites, like a different version of BAML or imcompatibility with other mods? (the 6.1 release did work ok previously albeit without FBT).

**Comment by nicoco007** [comment]
That might be because I've also updated something in DynamicOpenVR at some point, so you would also need to update that from [here](https://ci.gnyra.com/job/DynamicOpenVR/job/master/129/artifact/DynamicOpenVR-79564d4-RELEASE.zip) and [here](https://ci.gnyra.com/job/DynamicOpenVR/job/master/129/artifact/DynamicOpenVR.BeatSaber-79564d4-RELEASE.zip) (DynamicOpenVR has been separated in two, you need to install both).

**Comment by TsukikoChan** [comment]
Will give that a go this weekend at some point Nico, I've extracted all into my beatsaber folder.

**Comment by seguraf16** [comment]
I tried out this version and it gave a pop up with the new input system it would use, after hitting yes to allow it to do so, in game none of the controllers are picked up. Looking at the keybinds through the dashboard it sits there loading and dosent display the ones for beat saber. Selecting the ones for the dashboard works as aspected.

> That might be because I've also updated something in DynamicOpenVR at some point, so you would also need to update that from [here](https://ci.gnyra.com/job/DynamicOpenVR/job/master/129/artifact/DynamicOpenVR-79564d4-RELEASE.zip) and [here](https://ci.gnyra.com/job/DynamicOpenVR/job/master/129/artifact/DynamicOpenVR.BeatSaber-79564d4-RELEASE.zip) (DynamicOpenVR has been separated in two, you need to install both).

**Comment by TsukikoChan** [comment]
Tried it at the weekend, it also had a popup the first time used, i hit yes and the avatars are showing again and customisable but T-Posing now, not even following the normal head/hands controllers.

**Comment by nicoco007** [comment]
Sorry, my bad. I linked the wrong stuff and the versions weren't in sync. These should work together:
* [Custom Avatars](https://ci.gnyra.com/job/BeatSaberCustomAvatars/job/develop/98/artifact/BeatSaberCustomAvatars-d7f5bc4-RELEASE.zip)
* [DynamicOpenVR](https://ci.gnyra.com/job/DynamicOpenVR/job/master/132/artifact/DynamicOpenVR-5fd09c6-RELEASE.zip)
* [DynamicOpenVR.BeatSaber](https://ci.gnyra.com/job/DynamicOpenVR/job/master/132/artifact/DynamicOpenVR.BeatSaber-5fd09c6-RELEASE.zip)

**Comment by TsukikoChan** [comment]
Thank you, i tried those out this evening. Now the avatar moves as before (wrists feel better too) but FBT does not work still, also when i load in there's now one or two white cubes in the center of the play area (about head height) inside BeatSaber.
Also, to note, SteamVR seems to have been updated in the last day so there's a possibility this might be interesting too.

**Comment by nicoco007** [comment]
The white cubes are once again my bad, I forgot to remove that after trying to figure something else out. I just released [Custom Avatars](https://github.com/nicoco007/BeatSaberCustomAvatars/releases/tag/v5.0.0-beta.7) and [DynamicOpenVR](
https://github.com/nicoco007/DynamicOpenVR/releases/tag/v0.2.0) for Beat Saber 1.8.0. Could you try it out with those and let me know how it goes? Also, try clearing full body tracking data ("Clear" button in the avatars menu) since that might be messing with stuff.

**Comment by TsukikoChan** [comment]
Hi Nico,
I tried the new version a few times. The white boxes are gone and the avatar is working back to what it was previously (with wrists pointing the right way now too), but still no compatibility with driver4vr created pucks/vivewands. SteamVR shows the wands at the right place (hips and feet) but nothing being taken into BeatSaber, even with clear data, calibrating and calibrating on startup. So no real change on the FBT yet.
On the plus side, some older avatars that didn't work now work!

**Comment by TsukikoChan** [comment]
Oh, just a thought, is there any way of enabling a debug logging version of the plugin, to see what is going wrong so i can pass that text log file / eventlog entries to see why the driver4VR data isn't working as fbt?
A new version of Driver4VR came out this week, I'll do another wee test of the setup this week.
Again, thanks for all the hard work so far Nico.

**Comment by nicoco007** [comment]
Sorry, wasn't paying attention. I'm going to be re-testing this soon.
