### ISSUE TITLE
Certain Custom Avatars Are Headless to CameraPlus

### ISSUE THREAD

**Issue by Fidgetcetera** [nicoco007/BeatSaberCustomAvatars#41]
[_latest.log on a non-working version](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4874482/_latest.log)
[_latest.log on a working version](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4874492/_latest.log)
**Desktop (please complete the following information):**
- Operating system: Xubuntu 20.04
- Headset and controllers: HTC Vive

**Extra Versioning Info:**
CameraPlus 4.20 (The standard snow12 build on Beatmods)
BeatSaberCustomAvatars Jenkins Build of Commit 9cd38f9 (I got impatient about the floor height adjustment bugfix)

**Describe the bug**
Certain avatars are headless as seen by CameraPlus. An example of this can be seen with:
https://modelsaber.com/Avatars/?id=1560290521&pc
This is working in release 5.0.0-beta 7, as well as the release used by BeatSaberMultiplayer's install guide, or I'd aim at it being a bug with cameraplus. 

**Steps to reproduce**
1. Add and use custom avatar.
2. Use third person camera in CameraPlus.
3. Fail to see head. 

**Expected behavior**
Avatars should show up normally to the camera.

**Screenshots**
Broken:
![Hatsune miku, headless besides twintails with the bases surrounded by glowing square outlines.](https://user-images.githubusercontent.com/15249812/86526297-6478d600-be60-11ea-8022-995648ebf9b8.png)
Working:
![Hatsune miku without the bug, mostly normal with some clipping of physics on a dress. She's got a head attached to the twintails though.](https://user-images.githubusercontent.com/15249812/86526320-a73aae00-be60-11ea-9ff4-d46042adc2c1.png)

**Comment by Fidgetcetera** [comment]
It looks like the broken builds are getting "Type provided must be an Enum" errors on the avatar. That seems to be the primary difference at a glance?

**Comment by nicoco007** [comment]
This is actually 2 separate issues. The missing heads are caused by a change to the layers used by the avatars since there were some conflicts with internal Unity and Beat Saber stuff. Since CameraPlus doesn't reference these directly, they'll also have to be updated on its end. The type errors in the log are because of an oversight on my part and have now been fixed.
