### ISSUE TITLE
FBT calibration

### ISSUE THREAD

**Issue by ghostiekitty** [nicoco007/BeatSaberCustomAvatars#42]
The avatar that I use when trying to configure full body just stands in the A-Pose.  No way to get it to track in any way.  It's not my avatar so I can't really give any details on it.

**Comment by nicoco007** [comment]
Could you provide your latest log and, if possible, a link to the avatar you're using?

**Comment by ghostiekitty** [comment]
Seems like it was removed from modelsaber so I uploaded it to drive.
https://drive.google.com/file/d/1x95vE84ufnhfqDyVjYABaXRHm1j6DYD6/view?usp=sharing
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4943181/_latest.log)

**Comment by nicoco007** [comment]
Could you try [this version](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4945299/BeatSaberCustomAvatars-b355974-RELEASE.zip) and let me know if it works?

**Comment by ghostiekitty** [comment]
I can give it a try when I get home from work.  Thank you.

**Comment by ghostiekitty** [comment]
Yup that one works perfectly good job.

**Comment by nicoco007** [comment]
Great! This'll be included in the next release. Feel free to continue using the version I posted in the meantime.
