### ISSUE TITLE
Patched Cam+ | Avatar pop-in and invisible in menu.

### ISSUE THREAD

**Issue by FEFELAND** [nicoco007/BeatSaberCustomAvatars#43]
**Desktop (please complete the following information):**
- Operating system: Windows 10
- Headset and controllers: Valve Index Full Kit

**Describe the bug**
Not exactly an issue with the avatar plugin itself, but the patched Camera+
1. After going into a song, it takes a little bit for the avatar to spawn. It's just the sabers for a sec.
2. When going back to song selection, the avatar remains invisible. At least until I reload or switch camera profile.

**Steps to reproduce**
1. Load song and watch the game preview on desktop(ThirdPerson). There will be a short delay before avatar pops in.
2. Go back to menu.
3. To make it show again, go to profiles and hit load or switch to a different one if you have any. Toggle hide/show avatar works too.

**Expected behavior**
1. I've never seen an avatar "pop" in after loading a song. 
2. Avatar shouldn't really ever go invisible. Only place I can think of where it should, is during replays.
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4943172/_latest.log)

**Comment by nicoco007** [comment]
Could you try [this version](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4945175/CameraPlus.zip) instead?

**Comment by FEFELAND** [comment]
Oh, it's almost good! Went from a major issue to a minor thing.
That minor thing being:
As soon as one hits play, there's some kind of jerky motion. Very noticeable if the avatar has dynamic bones.
Can be seen here: 
https://streamable.com/7qw4a3

**Comment by nicoco007** [comment]
Could you try [this version](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4945299/BeatSaberCustomAvatars-b355974-RELEASE.zip) and let me know if it works?

**Comment by nicoco007** [comment]
Woops, wrong issue, haha.

**Comment by nicoco007** [comment]
I think I know why that's happening. Could you open a second issue for this? It's not really related to the original problem you were having and it would make it easier for me to keep track of what's going on.

**Comment by nicoco007** [comment]
Thanks! Closing this issue since the original problem was resolved.
