### ISSUE TITLE
Jerky motion after hitting "Play" on a song.

### ISSUE THREAD

**Issue by FEFELAND** [nicoco007/BeatSaberCustomAvatars#45]
A minor, but noticeable issue:
As soon as one hits play, there's some kind of jerky motion. Very noticeable if the avatar has dynamic bones.
Can be seen here:
https://streamable.com/7qw4a3

**Comment by nicoco007** [comment]
Could you try [this version](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4957987/BeatSaberCustomAvatars-46d73a3-RELEASE.zip) and let me know if it works?

**Comment by FEFELAND** [comment]
Everything seems to be working as intended now! Thank you very much!
Also updated the title since it seems like it was an avatars issue instead of a cam+ one.

**Comment by nicoco007** [comment]
Thanks for taking the time to report these!
