### ISSUE TITLE
Avatar just standing there on Rift S in beta8 only.

### ISSUE THREAD

**Issue by simeng** [nicoco007/BeatSaberCustomAvatars#46]
[2020.07.21.19.19.25.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4955255/2020.07.21.19.19.25.log)

**Desktop (please complete the following information):**
- Operating system: Windows 10
- Headset and controllers: Oculus Rift S

**Describe the bug**
Lost total control over the avatars on all avatars including the template ones from the zip.

Seems to crash when loading tracking:
[CRITICAL @ 19.19.40 | UnityEngine] NullReferenceException: Object reference not set to an instance of an object
[CRITICAL @ 19.19.40 | UnityEngine] CustomAvatar.Tracking.OpenVRWrapper.GetStringTrackedDeviceProperty (System.UInt32 deviceIndex, Valve.VR.ETrackedDeviceProperty property) (at <5444f1769cc247da88395f173d83419f>:0)
[CRITICAL @ 19.19.40 | UnityEngine] CustomAvatar.Tracking.OpenVRWrapper.GetTrackedDeviceSerialNumbers () (at <5444f1769cc247da88395f173d83419f>:0)
[CRITICAL @ 19.19.40 | UnityEngine] CustomAvatar.Tracking.TrackedDeviceManager.UpdateInputDevices () (at <5444f1769cc247da88395f173d83419f>:0)
[CRITICAL @ 19.19.40 | UnityEngine] CustomAvatar.Tracking.TrackedDeviceManager.Start () (at <5444f1769cc247da88395f173d83419f>:0)

**Steps to reproduce**
1. Started beat saber
2. Avatar just stands there (or runs away, but only a few of them do but I guess that's just a avatar bug when manager is not attached)

I tried with both DynamicOpenVR 0.2.1 and 0.2.0 with beta.8 with no but as soon as I downgraded BeatSaberCustomAvatars to beta.7 it worked again.

**Expected behavior**
Moving headset or controllers moves the avatar.

**Comment by simeng** [comment]
Just adding that I tried running Beat Saber with -vrmode oculus and without with same result.

**Comment by nicoco007** [comment]
Could you try [this version](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4957332/BeatSaberCustomAvatars-de39caf-RELEASE.zip) and let me know if it works? If it doesn't, could you attach the latest log after running that version?

**Comment by simeng** [comment]
That version works like a charm!

**Comment by nicoco007** [comment]
Great! The fix will be included in the next release. Feel free to use this version until then.
