### ISSUE TITLE
Tracking doesn't work with -vrmode oculus

### ISSUE THREAD

**Issue by Ikeiwa** [nicoco007/BeatSaberCustomAvatars#48]
**Log**
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4977856/_latest.log)

**Desktop:**
- Operating system: Windows 10
- Headset and controllers: Oculus Rift cv1

**Describe the bug**
When running the game using "-vrmode oculus" the tracking doesn't work at all and the avatar stays in T-Pose.

**Steps to reproduce**
1. add "-vrmode oculus" to the startup options in steam
2. Run the game and see the avatar in T-Pose

**Expected behavior**
Tracking should work

**Comment by nicoco007** [comment]
Looks like the same problem as in #46. Could you try [the version I posted in this comment](https://github.com/nicoco007/BeatSaberCustomAvatars/issues/46#issuecomment-662191487)?

**Comment by Ikeiwa** [comment]
Yep! It works perfectly with this version.

**Comment by nicoco007** [comment]
Great!
