### ISSUE TITLE
avatar is not tracking with headset and controllers only. 

### ISSUE THREAD

**Issue by amatsuki12** [nicoco007/BeatSaberCustomAvatars#50]
I can see the avatar but it will not track with my controller or headset. It just does a T pose. I tried to go through all the tab to see if I can make it move but nothing worked. Not sure if i download and install the mod incorrectly.

**Comment by nicoco007** [comment]
Could you please attach your latest log? It's the file called `_latest.log` inside the `Logs` folder of your Beat Saber install.

**Comment by prax4788** [comment]
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5046576/_latest.log)
I been having the same problem here is mine hope it helps   
I also can't see my avatar unless I turn it on to see it in first person

**Comment by nicoco007** [comment]
Looks like the same problem as in #46. Could you try [the version I posted in this comment](https://github.com/nicoco007/BeatSaberCustomAvatars/issues/46#issuecomment-662191487)?

**Comment by nicoco007** [comment]
Closing since I haven't heard from the original author in over 2 weeks.

**Comment by ZombieBrine13092** [comment]
This also happens with the [Neko Pink](https://modelsaber.com/Avatars/?id=1555354983&pc) avatar. Does not track at all, in a t-pose and floating a bit. It does however track in older versions of CA, for whatever reason.

**Comment by nicoco007** [comment]
There are certain avatars like Neko Pink that were exported using an older version of Unity (usually 2018.4) and can no longer be imported properly by the newer version of Unity the game is now using (2019.3 at the time of writing). Unfortunately there's nothing I can do about it; the data that isn't being loaded properly is internal and there's no way for me to access/interpret it.
