### ISSUE TITLE
EveryNthComboFilter doesn't work

### ISSUE THREAD

**Issue by ranmd9a** [nicoco007/BeatSaberCustomAvatars#55]
**Before doing anything else, please attach your latest log to this issue. It should be located at `Logs\_latest.log` in your Beat Saber installation's folder.**
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5065788/_latest.log)

**Desktop (please complete the following information):**
- Operating system: Windows10
- Headset and controllers: Oculus Rift S (-vrmode oculus)

**Describe the bug**
I use CustomAvatar.dll of [this version](https://github.com/nicoco007/BeatSaberCustomAvatars/issues/46#issuecomment-662191487).
However, the event set in EveryNthComboFilter does not work.
(EveryNthComboFilter worked with CustomAvatar.dll 5.0.0 beta7)

**Steps to reproduce**
1. Use an avatar that set EveryNthComboFilter,
2. Play any song.
3. 50 combo reached, but the event not fired.

**Expected behavior**
EveryNthComboFilter work.

**Comment by nicoco007** [comment]
Good catch! Could you try [this version](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5066319/BeatSaberCustomAvatars-77d1262-RELEASE.zip) and let me know if it works?

**Comment by ranmd9a** [comment]
Thank you for your fast response!
But when I used that version, the avatar disappeared.

latest.log is here.
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5066577/_latest.log)

I deleted a cameraplus.cfg just in case and started BeatSaber, but the avatar was not shown.
And I used DynamicOpenVR 0.2.0 by mistake, but it was the same with 0.2.1.

**Comment by nicoco007** [comment]
That's strange. Can you see it in the mirror when in the Avatars menu? I forgot to mention that the version I linked doesn't currently work properly with CameraPlus.

**Comment by ranmd9a** [comment]
Oh, I can see the avater in Avatars menu.
It may be a problem of CameraPlus as you say.

**Comment by nicoco007** [comment]
[This version](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5078234/BeatSaberCustomAvatars-3764aed-RELEASE.zip) should work properly with CameraPlus. Could you try it out?

**Comment by ranmd9a** [comment]
It works, and the avatar did not disappeare! Thank you so much!
