### ISSUE TITLE
beta8 breaks campaign modes, while beta 7 works as intended

### ISSUE THREAD

**Issue by KaladinStormrunner** [nicoco007/BeatSaberCustomAvatars#57]
The latest log I have is of beta7 where things are working normally. If you would like me to reproduce the issue and provide a log, let me know. 
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5077161/_latest.log)

**Desktop (please complete the following information):**
- Operating system: Windows 10
- Headset and controllers: Oculus Rift S

After installing beta8 and dovr campaign modes break (both custom and normal) such that the ending screen will not appear and the user is dumped back on to the campaign song selection screen. This results in no progress being made through campaigns. Installing beta7 restores normal functionality. 

**Steps to reproduce**
1. Download and install the beta8 version and dovr v0.2.1-release
2. Extract files and drag into Beat Saber steam directory
3. Replace any existing files
NOTE: This behavior is unchanged when dovr.beatsaber is installed. Furthermore selecting "No Avatat" in the avater mod menu restores functionality. 

**Expected behavior**
Avatars should work while playing campaign modes, and a results screen should appear at the end of a song.

**Comment by nicoco007** [comment]
Looks like this is the same issue as #56 so I'm closing this and will post updates there. I've put up a version that might fix the problem; feel free to contribute any additional information you might have there.
