### ISSUE TITLE
Feet clipping through the floor

### ISSUE THREAD

**Issue by fuyushi** [nicoco007/BeatSaberCustomAvatars#59]
When starting up the game my avatars feet clip through the floor. Upon entering the avatar menu it immediately fixes itself for the game menus, but when going into a song the feet are clipping there again. Coming out of the song the feet in the menu are working properly again.

**Comment by nicoco007** [comment]
I can confirm this is indeed an issue! It will be fixed in the next release. Thanks for the report!

**Comment by nicoco007** [comment]
Fixed in f6b6ebc which will be included in the next release.
