### ISSUE TITLE
calibration results in a twisted body (Driver4VR)

### ISSUE THREAD

**Issue by orangpelupa** [nicoco007/BeatSaberCustomAvatars#6]
On Beta 4 and Beta 3, pressing the calibration button on avatar menu will make the body twisted if you are using Driver4VR (if using sharky20 kinecttovr, the body didnt go twisted).

Workaround fix:
openvr input emulator can manually offset the "Twist" on Beta 3 (on Beta 4, the driver yaw/rotation/skew offset no longer works, only x y z)

**Comment by nicoco007** [comment]
Going to close this since it's very closely related to #4.
