### ISSUE TITLE
Avatar height problem while calibrating FBT

### ISSUE THREAD

**Issue by intbla** [nicoco007/BeatSaberCustomAvatars#61]
**Before doing anything else, please attach your latest log to this issue. It should be located at `Logs\_latest.log` in your Beat Saber installation's folder.**
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5114640/_latest.log)

**Desktop (please complete the following information):**
- Operating system: Windows 10
- Headset and controllers: Valve Index

**Describe the bug**
As soon as I press calibrate, the avatar gets lifted up a bit. The foot trackers are beneath the avatar then. If I offset the floor so that the trackers are on the right position on the avatar, the avatar floats in the air after calibrating.
This occurs with almost all custom avatars I tried from modelsaber.com. Only the FBT Template Avatar is showing the foot trackers at the right position.
Here's an example of an avatar causing the bug: https://modelsaber.com/Avatars/?id=1560290521&pc
When downgrading to BS 1.10. and Custom Avatars Beta 8, the foot trackers are at the right position again.

**Steps to reproduce**
1. Go to Custom Avatar settings
2. Click on Calibrate
3. See avatar getting lifted in the air

**Expected behavior**
The avatar not being lifted in the air when pressing calibrate.

I can provide screenshots or a short video of the problem if needed.

**Comment by nicoco007** [comment]
I think I see what you're describing but just to clarify, do the feet float after you've pressed *Calibrate* and then *Save* or just after *Calibrate* ?

**Comment by nicoco007** [comment]
I've shipped a potential fix in [5.0.0 RC 2](https://github.com/nicoco007/BeatSaberCustomAvatars/releases/tag/v5.0.0-rc.2), could you try it out and let me know if that works?

**Comment by intbla** [comment]
Sorry, couldn't play for a couple of days.
Just tested it and it looks great. Tried a few avatars and none of them was lifted up in the air when pressing Calibrate. Thank you for the fix!

**Comment by nicoco007** [comment]
Great!
