### ISSUE TITLE
An option to lock avatar feet in place

### ISSUE THREAD

**Issue by ZombieBrine13092** [nicoco007/BeatSaberCustomAvatars#62]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
An option to lock avatar feet in place.

**Describe alternatives you've considered**
I have tried messing with openvr input emulator, to no avail

**Comment by nicoco007** [comment]
Sorry about the long wait. This is definitely possible; I'll try to get something in for the next release.

**Comment by nicoco007** [comment]
I've added a setting called "Enable Locomotion" which is enabled by default; you can uncheck it to lock the avatar's feet in place. It'll be included in the next release.
