### ISSUE TITLE
Limp wristed grip / odd grip angles?

### ISSUE THREAD

**Issue by djicode** [nicoco007/BeatSaberCustomAvatars#68]
Have you ever looked in to the issue with the weird grips where the hands are almost hanging off the sabers like rag-doll physics?
I'm not talking about if the model was rigged wrong and the attach point was at the wrong angle. The sabers are pointed in the right direction related to the model/wrist.

I disassembled and looked at the source and it seems like the issue is either the avatars don't have some kind of weight assigned to the wrist with IK so the wrist just collapses/hangs or it could be differences between the controller tracking with oculus or vive or a combination of both. 

I'm interested in solving this issue although it could be difficult with improperly rigged models, any input is welcome.

**Comment by djicode** [comment]
If it's a location/vector tracking issue difference between oculus and vive I think it could be solved with a vector offset tied to a configuration toggle but I haven't had issues in any other cross platform games. Maybe it's just most models are rigged incorrectly?  Otherwise it has to be IK doing some weird stuff with the wrist because of the rigging which I'm not even sure if you can fix at runtime.

**Comment by nicoco007** [comment]
Does this happen with all avatars? If it only happens with a specific one, could you attach it here so I can take a look?

I usually use the included "Template &ndash; Full Body" avatar that's included with the mod as the "gold standard," so if you're also having trouble with that one it's definitely a bug. If you're not, it's usually an issue with rigging or configuration in Unity when creating the avatar which unfortunately can't be corrected at runtime.

The mod uses the same position and rotation offsets as the base game for controllers and nothing else, so I highly doubt that's the issue here.

**Comment by djicode** [comment]
Of course the whole point of Inverse Kinematics is to mimic the way the human body and physics works. Weight / tolerance applied to joints so that they mimic actual humanoids. So far, to answer the above, most avatars, but it's worse with some. Only tested about 5 so far.

**Comment by djicode** [comment]
![image](https://user-images.githubusercontent.com/11299613/93273214-5c54e500-f785-11ea-9320-fd3995ee573a.png)
Hard to see on this one, but it's like an inside grip. I have calibrated arm length. Maybe something to do with calibrated arm length vs avatar arm length. I will post more.

**Comment by djicode** [comment]
![image](https://user-images.githubusercontent.com/11299613/93273437-da18f080-f785-11ea-91f0-0006d9ee28d5.png)
It's like the wrists are being bent backwards.

**Comment by djicode** [comment]
Like maybe the arm length calibration is off. I will re-calibrate and test the same avatar again.

**Comment by djicode** [comment]
I checked 30 different models and only like 5 of them were correct. I'm 100% certain it has nothing to do with IK or the plugin. It's the attachment angles on the avatars themselves that are incorrect. "Template – Full Body" is indeed perfect. Now I wonder if it's possible to offset these at runtime on a per model basis?

**Comment by djicode** [comment]
No worries, I'll so some playing and If I come up with any AhHah moments, I'll keep you posted. 😉

**Comment by djicode** [comment]
Ie, I also noticed that grip type also plays a part,, it wouldn't be a bad idea to be able to "calibrate" that as it would vary based on person, grip, hand size, etc. assuming that's something that could be offset at runtime.

**Comment by djicode** [comment]
So I think in LoadedAvatar before it's spawned it would be possible to check and add a transform offset to "this._leftHand = this.prefab.get_transform().Find("LeftHand");" before the avatar is spawned.

**Comment by nicoco007** [comment]
What you're describing is definitely possible, but it would add another layer of complexity to the already somewhat confusing tracking/calibration system and honestly shouldn't be necessary as long as avatars are made properly. As far as I can tell, you're the first person to have this issue so I'm guessing this is either a problem specific to the controllers you're using or somewhere in your configuration.

For now, from what I can tell based on the images you shared, it looks like the sabers are rotated 180° or so around the top/bottom axis of the sabers. Could you try going into *Settings* > *Controllers* and adjusting the *Rotation Z* slider to see if that helps?

**Comment by djicode** [comment]
I don't think it would add complexity to the tracking/calibration system because the value gets adjusted when the model is loaded. Well, unless you wanted to make real time adjustments and needed to take in to account the calibration. I don't think many people say anything about it or even care, 75% of the videos I see online have broken wrist syndrome, lol. It's not all avatars, I think many are just not made properly and then there is no way to adjust for grip. 

Editing settings -> controllers does work, but it would bork other games if you're just adjusting for grip etc in beat saber.

No worries, I already figured out how to adjust the initial transform in code when the avatar is loaded. If I get too annoyed by it I'll figure out how to save and load transform offsets by avatar. Awesome plugin by the way!

**Comment by nicoco007** [comment]
When I said _Settings_ > _Controllers_, I was talking about Beat Saber's in-game settings, not SteamVR or Oculus' settings. That wouldn't change anything related to other games.

The "broken wrist syndrome" I've seen on most avatars is just because some avatar creators don't take into account that controllers (and therefore sabers) are held at a slight angle (around 30°)  and not completely perpendicular to the fingers. Is that what you're talking about? I've yet to see someone's hands be completely flipped like what you've got in your screenshots.

I hope this isn't coming off as hostile - I'm just trying to figure out why this hasn't been brought up before!

**Comment by djicode** [comment]
No worries, I was confused about the settings and wasn't thinking, it was a long day at work. They would be beat saber specific and could be used to adjust for controller grip.

I completely agree at this point about the majority of issues being that the transform's for hand targets are off to begin with. "Template – Full Body" works perfectly well with a normal grip and you could easily account for custom grip styles in Beat Saber's settings.

Honestly it would probably be easier to edit the Avatar's hand target transforms than try to account for it in game so your completely correct with thinking it would be more trouble than it's worth. Problem solved, lol.

**Comment by nicoco007** [comment]
Okay great, glad we're on the same page haha. I think we've managed to answer your original question so unless you have any other related questions I'll close this issue.

**Comment by djicode** [comment]
Closed, is good. The only other issue I have seen is the feet in the floor but there is already a bug ticket for that. Thanks for all your hard work and the awesome plugin!
