### ISSUE TITLE
Avatar stuck in t-pose, arms not moving (Oculus Rift S)

### ISSUE THREAD

**Issue by BlakMushRoum** [nicoco007/BeatSaberCustomAvatars#7]
As the title say, my avatar is stuck in a t-pose position. The body and arms don't follow my movements. 
I kept the default avatar, but I have the same problem with other avatars.
I tried to uninstall and reinstall properly, to no avail.
![ScreenshotBS](https://user-images.githubusercontent.com/59623777/71925686-e4640300-3191-11ea-90a6-c5906b2b3d2f.png)

**Comment by nicoco007** [comment]
Could you attach your latest log? It should be inside the `Logs` folder of your Beat Saber folder.

**Comment by BlakMushRoum** [comment]
There you go, I hope this will be helpful.
Thanks for responding so quickly !

[2020.01.07.21.17.28.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4032346/2020.01.07.21.17.28.log)

**Comment by BlakMushRoum** [comment]
There, I hope this will be helpful.
Thanks for responding so quickly.
[2020.01.07.21.05.22.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4032352/2020.01.07.21.05.22.log)

**Comment by nicoco007** [comment]
I can't check right now but it looks like it's just an issue with the game's 1.6.1 update. I should be able to get this fixed later today.

**Comment by BlakMushRoum** [comment]
Alright, I'll be waiting in the meantime.
Besides, all my songs are broken because of the update.
Seems more like bad timing than anything else I suppose.

**Comment by nicoco007** [comment]
This should now be fixed in [beta 5](https://github.com/nicoco007/BeatSaberCustomAvatars/releases/tag/v5.0.0-beta.5).

**Comment by LordDamionDevil** [comment]
For some reason this also happens with the Rift the log does show that it detects the devices correctly but for some reason the avatars are stuck in a t-pose

**Comment by BlakMushRoum** [comment]
In any case, the bug seems to be resolved for me. 
Thanks for the assistance !
