### ISSUE TITLE
No tracking

### ISSUE THREAD

**Issue by Bco1981** [nicoco007/BeatSaberCustomAvatars#73]
Beat Saber Log: https://justpaste.it/4756v
CustomAvatar Log: https://justpaste.it/43711

**Desktop (please complete the following information):**
- Operating system: Windows 10 x64 Pro
- Headset and controllers: Oculus Rift CV1, Touch controllers gen1, 2x HTC Vive base station 2.0, 3x HTC Vive trackers.

**Describe the bug**
Trackers are not detected in Beat Saber. Goes for any avatar.

**Steps to reproduce**
1. Load Oculus home
2. Load SteamVR
3. Turn on trackers one by one in the order of left foot, right foot, waist.
4. Load Beat Saber 1.12.2 (fresh install, then added updated 1.12.2 mods)
5. No leg tracking on models.

**Expected behavior**
I see this in the Beat Saber 1.10 log.
[INFO @ 18:40:50 | Custom Avatars] Using device "VIVE Tracker Pro MV S/N LHR-D84A94EA" as LeftFoot
[INFO @ 18:40:50 | Custom Avatars] Using device "VIVE Tracker Pro MV S/N LHR-A6397F86" as RightFoot
They are not identified as left or right foot in the latest log.

**Screenshots**
https://youtu.be/JAp6uKmZgo8

**Comment by nicoco007** [comment]
Have you assigned tracker roles in SteamVR? You should be able to check by opening SteamVR's settings, going to "Controllers", then "Manage Vive Trackers." For a tracker to be assigned by Custom Avatars properly, it needs to be set to one of *Waist*, *Left Foot*, or *Right Foot*.

**Comment by Bco1981** [comment]
But i can roll back my Beat saber to 1.10 and then they work ?

**Comment by Bco1981** [comment]
I haven't, i didn't know that, that was necessary since it worked fine with 1.10, and suddenly stopped from 1.11. So i stayed at 1.10 because that still worked. But i will look into it tomorrow.

**Comment by Bco1981** [comment]
Sorry for my ignorance, it works after assigning the roles.
But there was no place i was informed of this was needed. Since it worked with vrchat, and worked in BS 1.10. and then suddenly just stopped working from BS 1.11

**Comment by nicoco007** [comment]
Yeah, I definitely need to mention that somewhere. Sorry about that! I thought I had but I can't seem to find the release where I made it necessary so I guess I didn't!
