### ISSUE TITLE
[5.0.1] Dithered meshes missing from mirror?

### ISSUE THREAD

**Issue by Protected** [nicoco007/BeatSaberCustomAvatars#74]
**Before doing anything else, please attach your latest log to this issue. It should be located at `Logs\_latest.log` in your Beat Saber installation's folder.**
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5470135/_latest.log)

**Desktop (please complete the following information):**
- Operating system: Windows 10
- Headset and controllers: HTC Vive + Index controllers

**Describe the bug**
I don't honestly know if this is important enough to fix but I wanted to report just in case. My avatar's hair seems to be missing entirely from the mirror in the selection/settings page. It's visible in the main camera though!

**Steps to reproduce**
1. Go to the avatar settings page
2. Select avatar
3. Look at mirror

**Expected behavior**
Mirror reflects everything!

**Screenshots**
Video here: http://myshelter.net/bs/test.mp4
Only the beginning is relevant. Please ignore elbow oddities, I'm pretty sure those are on me.

**Comment by nicoco007** [comment]
This is just a side effect of how the mirror works around Beat Saber's transparency and bloom nonsense. I'm almost certain there's a way to get this working properly, I just haven't taken the time to look into it yet. I'll try to figure out a solution for version 5.1.0.

**Comment by IDarky** [comment]
Also have the problem with one of my avatars. But there it is because I used custom shaders which are not supported by Beatsaber. But since I see myself as an avatar without problems it is irrelevant for me since it is only the mirror. A bit annoying when calibrating FBT

**Comment by nicoco007** [comment]
I played around with this for a couple of hours and there unfortunately doesn't seem to be a perfect solution because of how Beat Games went about certain things (most likely for performance reasons). I'll try to investigate some more when I have time.

**Comment by nicoco007** [comment]
I'm going to take another look at this at some point in the next few weeks.

**Comment by nicoco007** [comment]
I've come to the conclusion that the only to get this working is to have an opaque mirror. It's kind of annoying but it's the only way to get an accurate reflection. I won't be adding it to 5.1.0 just because I've already been delaying that release for too long, but you can expect a fix in 5.2.0.

**Comment by nicoco007** [comment]
Fixed by 0a08d87 which will be included in the next release.
