### ISSUE TITLE
[5.0.3] Updating from previous version?

### ISSUE THREAD

**Issue by Protected** [nicoco007/BeatSaberCustomAvatars#75]
When trying to use the avatar I made for the/a previous version I noticed some warnings in the log files:

> [WARNING @ 02:26:38 | Custom Avatars] [LoadedAvatar(Zidane Tribal)] IKManager and IKManagerAdvanced are deprecated; please migrate to VRIKManager
> [WARNING @ 02:26:38 | Custom Avatars] [LoadedAvatar(Zidane Tribal)] Found VRIK on 'zidane2l'; manually adding VRIK to an avatar is no longer needed, please remove it
> [WARNING @ 02:26:38 | Custom Avatars] [AvatarDescriptor(Zidane Tribal)] Avatar is using a deprecated field; please re-export this avatar using the latest version of Custom Avatars

Obediently, I tried to replace CustomAvatars.dll in the project with the one in the EDITOR zip in the 5.0.1 release. When I started  unity, there were some errors in the console and the components in the avatar had failed to load. I tried removing them but that didn't get rid of the error, so I tried replacing the remaining files in the project with the ones in the project zip in the 5.0.1 release. Unity then complained that I was using the wrong version of Unity for the project, as it had been saved with Unity 2019. If I force it to open, I get even more errors. If I undo the changes to the project directory, I still get errors. I basically don't know how to rescue this project now, which is a bummer, since a lot of work has been put into it. What is the correct update procedure?

**Comment by Protected** [comment]
After a bunch of fooling around I really can't get this to work with the version of unity everyone's telling me to use, that being 2018.1.6f1

**Comment by Protected** [comment]
After a bunch of playing around I really can't get this to work with the version of unity everyone's telling me to use, that being 2018.1.6f1

**Comment by nicoco007** [comment]
Sorry for the delayed reply!

The new editor DLL should be a drop-in replacement in the old project, but you need to keep a couple of things in mind:
- You need to overwrite the existing `CustomAvatar.dll` file, not delete the old one and move the new one in. This is because of the way Unity deals with libraries &ndash; it assigns a unique identifier to the DLL when you copy it in the first time, and if you ever delete the DLL the identifier gets deleted along with it, causing "Missing Script" errors.
- You also need to copy `FinalIK.dll` and `DynamicBone.dll` from `Beat Saber_Data\Managed` in your Beat Saber install folder to the project, or else the Custom Avatars DLL won't load properly. I can't include these in the ZIP since they're paid assets in the Unity store.

The new Unity project that I've started including with releases uses Beat Saber's version of Unity, which is 2019.3.15f1 at the time of writing. The old Avatars project from Assistant's guide uses 2018.1.6f1 since it's nearly 2 years old at this point.

Hope that answers your questions! I'll be writing all of this on a documentation site I'm working on right now that'll come out in the near future along with instructions on how to use the new features.

**Comment by Protected** [comment]
Alright. I followed your instructions from a "working" (save for the weird elbow action) old project avatar. I installed 2019.3.15f1, made a copy of my project, changed it to use 2019.3.15f1, opened it, then replaced the dll with the latest one from 5.0.3. I got a bunch of warnings and a bunch of errors like these:

> Assets\Editor\CompileAvatarWindow.cs(32,11): error CS1061: 'AvatarDescriptor' does not contain a definition for 'Author' and no accessible extension method 'Author' accepting a first argument of type 'AvatarDescriptor' could be found (are you missing a using directive or an assembly reference?)
> Assets\Editor\CompileAvatarWindow.cs(33,11): error CS1061: 'AvatarDescriptor' does not contain a definition for 'Name' and no accessible extension method 'Name' accepting a first argument of type 'AvatarDescriptor' could be found (are you missing a using directive or an assembly reference?)

I noticed that the new project does not have an Editor folder. Any other steps I should be taking? Deleting things perhaps?

**Comment by nicoco007** [comment]
Yeah sorry, I forgot to mention you also need to delete the `Assets\Editor\CompileAvatarWindow.cs` file (you should be able to keep whatever else is in there though).

**Comment by Protected** [comment]
Ok, I deleted that, and also `EscapeXRSettingOnPlay.cs`, since there was a complaing about `PlayerSettings.virtualRealitySupported` being obsolete.

There were warnings related to missing scripts: All DynamicBoneColliders as well as DynamicBones that referenced colliders were missing, so I added them back by hand to their respective bones.

To the avatar, for now, I only added VRIK Manager (where I assigned the targets and position and rotation weights copied from the previous project) and First person exclusion (assigned to head, as in the previous project).

The only errors remaining on console pertain to OpenVR missing (and when trying to test, it tries to launch steamvr, which the old version didn't do).

That said, when I test, the hands and feet appear to be broken/twisted into an unnatural position:

![image](https://user-images.githubusercontent.com/1270823/99464486-2c19f600-2930-11eb-8e52-806e92ddb740.png)

This did not happen in the old version:

![image](https://user-images.githubusercontent.com/1270823/99464752-be21fe80-2930-11eb-9b6c-c8fb1c9122b4.png)

Any ideas?

**Comment by Protected** [comment]
Sorry, my bad! The targets were assigned to the controller objects. Reassigned them and everything's fine. (This wasn't a difficult problem, but I haven't had much time this week so I've been working on this in small portions. I'll try to test this in-game soon.)

**Comment by Protected** [comment]
Upon testing in-game, I'm experiencing the weirdest issue. When using the new project avatar, both eyes seem to render the same perspective for the avatar (so when my vision overlaps I see "double" - but *just* for the avatar). If I switch to the old avatar, it works fine. Ideas?

**Comment by Protected** [comment]
Solved the previous problem by scrubbing all XR plugins and extensions from the project, closing unity, reopening the project and reenabling legacy pipeline vr support, stereo rendering single pass. At this point I think I have parity with the old project, so I'm going to close this issue.

**Comment by Protected** [comment]
Wrong! I'm experiencing a weird issue now where all dynamic bone forces seem to apply to the avatar's reference coordinates rather than the world's reference coordinates. Any ideas?

Old (working as intended):
![image](https://user-images.githubusercontent.com/1270823/99910333-43b4fe00-2ce5-11eb-8ddf-3b180df33262.png)

New (Bone forces using avatar coordinate references):
![image](https://user-images.githubusercontent.com/1270823/99910337-49124880-2ce5-11eb-97c0-49677a683df5.png)

Ponytail and belt have a negative Y force and tail has positive Y forces at the end in both projects (exact same settings).

**Comment by nicoco007** [comment]
There's a lot of stuff that's done in-game to fix weird issues like this that isn't currenly applied within the Editor. It's something I'm planning on doing eventually; I'm just not sure how to approach it yet.

**Comment by nicoco007** [comment]
There's a lot of stuff that's done in-game to fix weird issues like this that isn't currenly applied within the Unity Editor. It's something I'm planning on doing eventually; I'm just not sure how to approach it yet.

**Comment by Protected** [comment]
Got it, thanks.
