### ISSUE TITLE
2-Tracker FBT working in LIV but not in Custom Avatars

### ISSUE THREAD

**Issue by zoetropik** [nicoco007/BeatSaberCustomAvatars#77]
Hi! First of all, thanks for maintaining the Custom Avatars mod; I was using it pretty much since it first came out.

A couple months back, I picked up a pair of used Vive Trackers to try FBT, and they worked fine for tracking my feet (strapped to my ankles) in LIV... but not in Custom Avatars. I've tried literally dozens of avatars downloaded from ModelSaber and only one of them ("Strong Knight FBT") will actually track my feet in Custom Avatars, whilst they all work fine in LIV.

I was unable to work out why this was happening, so eventually I gave up on Custom Avatars and was using LIV... but the most recent LIV update has caused the compositor to start crashing about 30 seconds into every song, so now it's unusable too.

I'm sure I must be missing something obvious or there would be more people complaining that FBT doesn't work in Custom Avatars. The only thing that occurred to me is that I haven't been able to get a third Vive tracker yet, so I wonder if Custom Avatars is unable to cope with just two Vive trackers on the ankles because it's expecting a waist input as non-negotiable?

But if so, then why does the "Strong Knight FBT" model track properly in Custom Avatars, even without the waist tracker?

Anyway, any help you can provide would be appreciated. I'd really love to get FBT working in Custom Avatars, but I have no idea what I'm doing wrong here, nor how to start troubleshooting it.

Many thanks in advance,
Zoë

**Comment by nicoco007** [comment]
Sorry for the delayed response! That's very strange, especially the fact that only one avatar is working as expected. I just checked and feet trackers only work properly on my end.

Are the avatars you've tried out all marked as FBT compatible? You also need to either calibrate full body tracking or bypass it in the Avatars settings menu under "Avatar Specific". If you don't, your feet will not be tracked at all. Have you done that?

**Comment by zoetropik** [comment]
Hi! Thanks for the reply. Sorry it took a couple days to get back to you; I've been swamped at work.

When I search the entirety of ModelSaber for "FBT", only 4 avatars (out of over a hundred) come back marked FBT-compatible. Is there a better place I should be searching for FBT-compatible avatars created/maintained by the Beat Saber community?

I downloaded / installed maybe forty avatars from ModelSaber just now and tested them in Custom Avatars. The four (incredibly ugly) ones marked FBT on ModelSaber all let me access "Calibrate" under the "Avatar Specific" menu and do track feet after I hit "Save". In addition, there are about four more avatars from ModelSaber that weren't marked FBT-capable which permit calibration. For all the rest, however, the "Calibrate" button stays greyed out and foot tracking is impossible.

Does Custom Avatars only support FBT for a total of 8 avatars across all those on ModelSaber? I'm trying to understand how LIV can "see" the bones in all these non-FBT-compatible avatars and work up IK for them, but Custom Avatars can't. I'm genuinely not trying to be difficult here; I'm just frustrated because I haven't done any programming in over a decade and don't know if I can teach myself enough Unity to make any of these avatars FBT-compatible with Custom Avatars. I foolishly assumed that if FBT worked for an avatar in LIV, it would also work in Custom Avatars.

Anyway, I don't want to eat up all of your time on this. I just was hoping there was some straightforward thing I could do to get any of these avatars working in Custom Avatars, but it looks like there isn't. Thanks again for taking the time to respond, and if you do know of a better repository of FBT-capable avatars that work with Custom Avatars, please point me in that direction, as it would be a lifesaver.

All the best,
Zoë

**Comment by nicoco007** [comment]
ModelSaber is the only model database for Beat Saber that I personally know of, although there might be other ones out there. Right now, Custom Avatars requires feet and waist targets to be set for full body tracking to work. That used to be important, but since I added calibration this should no longer be necessary. I have an idea as to how LIV might be handling it and it most likely would be rather easy to implement in Custom Avatars. I'll definitely get that done for 5.1.0.

**Comment by zoetropik** [comment]
Thanks again for your reply! I really appreciate it and am sorry for causing this extra hassle.

I confess I'm excited to hear you may have thought of a way to have Custom Avatars implement something like the LIV "waist-guessing" technique. I'll keep a lookout for 5.1.0 and whenever you do release it, I'll test it out ASAP and let you know if the FBT "Calibrate" button un-greys for the other ModelSaber avatars. That would be amazing! ;-)

Take care,
Zoë

**Comment by nicoco007** [comment]
Could you try out [this build](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5592849/BeatSaberCustomAvatars-abddf22-RELEASE.zip) and let me know if it works as expected? Note that this isn't an official release so other stuff might be broken.

**Comment by zoetropik** [comment]
Hi! Apologies for not spotting your message until just now. I've just downloaded the test build and will try installing it the next time my computer's booted into Windows (maybe tonight, but most likely tomorrow morning). Then I'll get right back to you with a report on whether FBT has started working on any of the non-explicitly-FBT-tagged avatars. Fingers crossed! ;-)

Thanks again and speak soon,
Zoë

**Comment by zoetropik** [comment]
Hi! Thanks for the reply. Sorry it took a couple days to get back to you; I've been swamped at work.

When I search the entirety of ModelSaber for "FBT", only 4 avatars (out of over a hundred) come back marked FBT-compatible. Is there a better place I should be searching for FBT-compatible avatars created/maintained by the Beat Saber community?

I downloaded / installed maybe forty avatars from ModelSaber just now and tested them in Custom Avatars. The four (incredibly ugly) ones marked FBT on ModelSaber all let me access "Calibrate" under the "Avatar Specific" menu and do track feet after I hit "Save". In addition, there are about four more avatars from ModelSaber that weren't marked FBT-capable which permit calibration. For all the rest, however, the "Calibrate" button stays greyed out and foot tracking is impossible.

Does Custom Avatars only support FBT for a total of 8 avatars across all those on ModelSaber? I'm trying to understand how LIV can "see" the bones in all these non-FBT-compatible avatars and work up IK for them, but Custom Avatars can't. I'm genuinely not trying to be difficult here; I'm just frustrated because I haven't done any programming in over a decade and don't know if I can teach myself enough Unity to make any of these avatars FBT-compatible with Custom Avatars. I foolishly assumed that if FBT worked for an avatar in LIV, it would also work in Custom Avatars.

Anyway, I don't want to eat up all of your time on this. I just was hoping there was some straightforward thing I could do to get any of these avatars working in Custom Avatars, but it looks like there isn't. Thanks again for taking the time to respond, and if you do know of a better repository of FBT-capable avatars that work with Custom Avatars, please point me in that direction, as it would be a lifesaver.

All the best,
Zoë

**Comment by zoetropik** [comment]
Okay, I've finally had a chance to Beat Saber again!

I just installed your test build and am happy to report it's cured the issue with the "Calibrate" button being greyed out. All of the previously non-FBT-able avatars I tested now permit calibration, and they seem to track fine. (The Pyra one has this weird thing happening where her epaulets seem to "flip around" on her shoulders if I rotate my wrists/forearms, but I'm guessing that's down to whoever originally created the model.)

I really appreciate you putting in the extra effort on this! I think it will end up helping a lot of other players, as now the full range of avatars available over on ModelSaber can be calibrated for FBT in Custom Avatar.

Anyway, I'm going to just hit "Comment" for now (rather than "Close with comment"), on the off-chance you want me to try out anything else with your test build before we close this thread. ;-)

Thanks a million,
Zoë

**Comment by nicoco007** [comment]
Great, thanks for confirming it works! You're most likely right about the shoulder issue &nbsp; most of the time, it comes down to issues with how the model was set up.

I don't think I have anything else related that needs testing so I'll close the issue. Thanks again for taking the time to report and test this!
