### ISSUE TITLE
fbt not working

### ISSUE THREAD

**Issue by Canine606** [nicoco007/BeatSaberCustomAvatars#78]
when I try to use FBT for the custom avatars it will shove the waist forward and turn my ankles facing inward on all the fbt compatible avatars i use

**Comment by IDarky** [comment]
Fullbody Tracking works great for me.I created the avatar myself with the Unity Project which is included in Release. I have not tested any public avatars you can find out there

**Comment by Canine606** [comment]
Is there suppose to be tracking orbs because I don’t see them


Sent from Yahoo Mail for iPhone


On Friday, November 13, 2020, 9:02 AM, IDarky <notifications@github.com> wrote:




Fullbody Tracking works great for me.I created the avatar myself with the Unity Project which is included in Release. I have not tested any public avatars you can find out there

**Comment by nicoco007** [comment]
Are you using manual calibration or the "Bypass Calibration" option? Also, could you please attach your latest log?

**Comment by Canine606** [comment]
what do you mean byu manual calibration 
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5543362/_latest.log)

**Comment by nicoco007** [comment]
If you press the "Calibrate" button under "Avatar Specific" (see below), a small sphere should appear where each of your trackers is. You can then align yourself with the avatar and press the "Save" button to save the calibration.

![image](https://user-images.githubusercontent.com/1349975/99201570-93da1080-2779-11eb-97e3-768a6fa83569.png)

**Comment by Canine606** [comment]
I don’t see that


Sent from Yahoo Mail for iPhone


On Sunday, November 15, 2020, 6:34 PM, Nicolas Gnyra <notifications@github.com> wrote:




If you press the "Calibrate" button under "Avatar Specific" (see below), a small sphere should appear where each of your trackers is. You can then align yourself with the avatar and press the "Save" button to save the calibration.

**Comment by nicoco007** [comment]
What do you mean exactly? Is it just the button that's missing or is the entire menu not there? If possible, could you post a screenshot of what you're seeing?

Are you using [the latest version of Custom Avatars](https://github.com/nicoco007/BeatSaberCustomAvatars/releases/latest)? Also, could you please attach your full latest log (the one directly inside `Logs`, not inside the `CustomAvatar` folder).
