### ISSUE TITLE
Floor Adjust breaks several environments' reflection

### ISSUE THREAD

**Issue by Jeremiidesu** [nicoco007/BeatSaberCustomAvatars#79]
**Before doing anything else, please attach your latest log to this issue. It should be located at `Logs\_latest.log` in your Beat Saber installation's folder.**
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5525528/_latest.log)

**Desktop (please complete the following information):**
- Operating system: Windows 10 2004
- Headset and controllers: Oculus Quest 1 over Oculus Link

**Describe the bug**
The mirror plane somehow moves down when looking down in several environments when floor is moved down by the plugin.

Environment list:
- Linkin Park
- FitBeat
- Green Day
- Green Day Grenade
- Panic
- Crab Rave
- Monstercat
- Dragons
- Origins

**Steps to reproduce**
1. Use any avatar that doesn't match your size
2. Enable Floor Height Adjust
3. Start a song with any environment mentioned above
4. Literally nod (look up and down) when something is reflected

**Expected behavior**
Reflection plane doesn't move.

**Screenshots**
[Video of the bug](https://cdn.platea.moe/Jeremii/2020/11/mirrorBug.mp4)

*Likely related: some non-affected environments also have their mirror plane snapping between two places: Big Mirror only has it when you look down to the point where you start looking behind you*

**Comment by nicoco007** [comment]
Thanks for the report! This will be fixed in the next release.

**Comment by nicoco007** [comment]
Fixed by 437d6b9 which will be included in the next release.
