### ISSUE TITLE
Nothing shows up in game (no settings button

### ISSUE THREAD

**Issue by Futuremappermydud** [nicoco007/BeatSaberCustomAvatars#8]
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4048944/_latest.log)

**Describe the bug**
So i installed the mod ran ipa like 5 different times restarted a couple times also

**Steps to reproduce**
1. Install mod on 1.6.2
2. Go in mods area to select avatars

**Expected behavior**
There should be a Custom Avatars button i can click to change my avatar

**Desktop (please complete the following information):**
- Operating system: Windows 10 (using oculus link so basically rift)

**Comment by LordDamionDevil** [comment]
Do you have DynamicOpenVR installed as I have noticed that your Log file states that it can't find the library of DynamicOpenVR

**Comment by nicoco007** [comment]
@LordDamionDevil is right; it doesn't look like the game is finding DynamicOpenVR. You can download the latest release [here](https://github.com/nicoco007/DynamicOpenVR/releases).

**Comment by Futuremappermydud** [comment]
i thought it came with dynamic open vr sorry
