### ISSUE TITLE
Avatar does not follow multiplayer spectator spot

### ISSUE THREAD

**Issue by Jeremiidesu** [nicoco007/BeatSaberCustomAvatars#80]
**Before doing anything else, please attach your latest log to this issue. It should be located at `Logs\_latest.log` in your Beat Saber installation's folder.**
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5533386/_latest.log) on 1.13.0

**Desktop (please complete the following information):**
- Operating system: Windows 10 20H2
- Headset and controllers: Oculus Quest 1 over Oculus Link

**Describe the bug**
When changing spectator spots, your avatar stays where you originally were 

**Steps to reproduce**
1. Play multiplayer
2. Fail / go to spectator mode
3. Move around and notice your avatar doesn't follow you

**Expected behavior**
Your avatar should follow you

**Screenshots**
![OculusScreenshot1605210985](https://user-images.githubusercontent.com/20820425/98998421-67828200-2536-11eb-8e0a-fb606defb5a1.jpeg)

**Comment by nicoco007** [comment]
Again, thanks for the report! This will be fixed in the next release.

**Comment by nicoco007** [comment]
Fixed by c619242 which will be included in the next release.
