### ISSUE TITLE
FBT Trackers not detected

### ISSUE THREAD

**Issue by Scribblingz** [nicoco007/BeatSaberCustomAvatars#81]
My trackers are not detected by custom avatars. Tried re-installing the game & mods and still having the issue.
Restarted my trackers, headset and Steamvr and still having the issue
The calibrate button always is grayed out and says not trackers detected.

Trackers work fine in VRChat.

Additional info: I am using the HTC Cosmos Elite

**Comment by Protected** [comment]
Not even with the placeholder avatar that comes with the mod? Did you assign roles to the trackers in the steamvr settings controllers section? That's something beat saber needs and vrchat doesn't.

**Comment by ilikecorndogs** [comment]
neither are mine. set up in steamvr correctly, using the template fbt avatar. index rather than vive, but i doubt that chanes much for vive hockey pucks

**Comment by ilikecorndogs** [comment]
after some fiddling, i found the previous version (5.0.2) worked flawlessly on 1.13 of beatsaber. no reason why, but its a workaround for now

**Comment by Scribblingz** [comment]
Placeholder didn't work, also assigning roles to the trackers also didn't work unfortunately. I'll try corndogs method next.

**Comment by nicoco007** [comment]
If you're still having trouble, could you please attach your latest log? It's the file called `_latest` inside the `Logs` folder (**not the one inside the `Custom Avatars` folder**) of your Beat Saber install.

**Comment by Scribblingz** [comment]
Still having issues. Here you go
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5582876/_latest.log)

**Comment by Protected** [comment]
You sure you assigned those tracker roles under settings, controllers, manage vive trackers?

Your log shows:

> [INFO @ 16:19:31 | Custom Avatars] [DeviceManager] Using device 'LHR-2E55DB6D' as Head
> [INFO @ 16:19:31 | Custom Avatars] [DeviceManager] Using device 'LHR-FFC75BC1' as LeftHand
> [INFO @ 16:19:31 | Custom Avatars] [DeviceManager] Using device 'LHR-FDFBBFC5' as RightHand

It should also contain:

> [INFO @ 16:19:31 | Custom Avatars] [DeviceManager] Using device '...' as Waist
> [INFO @ 16:19:31 | Custom Avatars] [DeviceManager] Using device '...' as LeftFoot
> [INFO @ 16:19:31 | Custom Avatars] [DeviceManager] Using device '...' as RightFoot

Where ... are LHR-1C6A35A4, LHR-776EF3E1 and LHR-10669A78 in any order. (I only have devices up to index 7 though, so maybe there's a limit or a something.)

**Comment by djgeloofficial** [comment]
I have the same issue i have my trackers on and ready and it is not working.

**Comment by Scribblingz** [comment]
They are assigned. Not sure what else I could do

**Comment by nicoco007** [comment]
Huh, that's weird. Could you please do the following:
1. Add `--trace` to the game's launch options (there are many guides on how to do it if you're not sure how). In the end, it should look like this:
    ![image](https://user-images.githubusercontent.com/1349975/100548307-b3713e80-3239-11eb-88fb-149d2334aab6.png)
2. Turn on all your trackers.
3. Run the game, wait for it to load, and close it.
4. Attach the new latest log here.
5. Remove `--trace` from the launch options (you'll end up with huge logs if you don't).

**Comment by rodsan0** [comment]
Hi! I'm having the same problem so [here](https://pastebin.com/j0JfMU07) are my logs with `--trace`. I'm using a bunch of mods so apologies for the length!   

Let me know what other steps I should take to help you debug this!

**Comment by Scribblingz** [comment]
There you go. Thanks for taking the time to help us
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5624642/_latest.log)

**Comment by nicoco007** [comment]
@rodsan0 It looks like your trackers are being detected properly. Can you double-check if full-body tracking works with the "Template &ndash; Full Body" avatar? Remember that you now need to calibrate using the button under "Avatar Specific" in the settings before full-body tracking applies.

@Scribblingz I'm not exactly sure what's going on in your case; for some reason, your trackers are still showing up as unassigned. Could you please tell me what version of SteamVR you're running and what devices you're using?

**Comment by Scribblingz** [comment]
SteamVR 1.15.12
HTC Vive Cosmos Elite (with HTC wireless adapter)
2 Vive wands
2 Base stations (1.0)
3 Vive trackers (2.0)

Also note: I did try to fresh install beat saber with just custom avatars and the required mods, but alas still got the issue

**Comment by djgeloofficial** [comment]
Any updates on getting this to work?

**Comment by Scribblingz** [comment]
I have no idea what I did, but it finally decided to work on its own. I haven't touched the game in weeks and I have no idea what changed

**Comment by djgeloofficial** [comment]
Im going to test it out soon and see if it works for me aswell. We will see

**Comment by djgeloofficial** [comment]
I got it to work in 5 0 2

**Comment by Okatsumo** [comment]
I ran into a similar problem.
Only one tracker works for me the one on my chest - while the others are ignored. The roles are set up correctly, and I’ve tried different versions of the game, from 1.39 to 1.40, but I didn’t notice any difference.
