### ISSUE TITLE
The legs become strange when the avatar squats。

### ISSUE THREAD

**Issue by pjwzhennba** [nicoco007/BeatSaberCustomAvatars#84]
The legs do not bend properly, they separate to the sides
![%W@KJQ@OED{ CJ%Z@P%M2YU](https://user-images.githubusercontent.com/75565299/101277330-a2eb3600-37ee-11eb-9da5-8858fce69964.png)
![1](https://user-images.githubusercontent.com/75565299/101277339-beeed780-37ee-11eb-9973-ba9915bf9a5c.png)
![3](https://user-images.githubusercontent.com/75565299/101277342-c1e9c800-37ee-11eb-8b38-18b1a25518f7.png)
![4](https://user-images.githubusercontent.com/75565299/101277343-c3b38b80-37ee-11eb-8b9c-bccc03e25305.png)

**Comment by pjwzhennba** [comment]
I'm confused. I Can't understand why this is。。。

**Comment by nicoco007** [comment]
It looks like the legs might be reversed (i.e. Unity thinks the left leg is the right one and vice-versa). This is easy to fix.

First, click on the model you imported in the Project panel. Then, in the Inspector panel, click on *Rig*, then *Configure*.

![a](https://user-images.githubusercontent.com/1349975/103311086-64a8f700-49e7-11eb-8ee9-33909ffbb8d0.png)

You should see something like below. Switch the bones listed under *Left Leg* with the ones under *Right Leg*. You can check it's done properly by clicking *Pose* > *Enforce T-Pose* at the bottom of the panel; the model should move to a standard T-pose (both arms stretched to either side of the body, both legs straight down, and no twisting of the torso). If it doesn't, check the bone assignments and try again. Once that's done, press *Done*.

If you're having trouble with this step, there are many tutorials on the Internet explaining in further detail what's going on in this window.

![b](https://user-images.githubusercontent.com/1349975/103311184-aafe5600-49e7-11eb-9f86-0816e921b6db.png)

Go back to the scene in which you're setting up the avatar and select the VRIK Manager component you added. Press the 3 dots on the top right, then press *Auto-detect References*. This will update the references to what you just changed in the previous step.

![c](https://user-images.githubusercontent.com/1349975/103311238-cb2e1500-49e7-11eb-92b4-afd39f1f20f2.png)

This should hopefully fix your problem.

**Comment by zenmetsu** [comment]
This has been closed, but the issue does not appear to be the legs getting swapped, the knees are simply crossing.  If anyone reads this in the future, the trick is to change the Swivel Offset in the VRIK Manager.  One leg will need to be negative, and you'll have to play with the angle until the legs remain straight forward/backward as the model crouches.

![image](https://user-images.githubusercontent.com/6358379/109259944-72e27c00-77ba-11eb-9128-4502cef0887d.png)

**Comment by kkkey21** [comment]
Thanks for sharing! But I wonder why can't my avatar squats? Everytime I squats it just maintains standing.
