### ISSUE TITLE
Avatar Export "fails" on Linux if using an uppercase avatar name

### ISSUE THREAD

**Issue by kitlith** [nicoco007/BeatSaberCustomAvatars#85]
Relevant Unity log:
```
FileNotFoundException: /tmp/DefaultCompany/Beat Saber Custom Avatars/BestBoi HD.avatar does not exist
System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) (at <437ba245d8404784b9fbab9b439ac908>:0)
CustomAvatar.Editor.AvatarExporterWindow.SaveAvatar (CustomAvatar.AvatarDescriptor avatar) (at <93cda637d1d9467cae7220dbd10478f3>:0)
CustomAvatar.Editor.AvatarExporterWindow.OnGUI () (at <93cda637d1d9467cae7220dbd10478f3>:0)
```

**Desktop:**
- Operating system: Arch Linux
- Headset and controllers: Valve Index, Knuckles controllers (not that it's relevant, since this is just in unity)

**Describe the bug**
When exporting an avatar, it is first exported to a temporary directory before being copied to its final destination.
Somehow, in the export step, the file is exported with a lowercase filename, which causes issues on case-sensitive filesystems commonly used on linux systems when you go to copy to the final destination. Thus, the copy fails.

**Steps to reproduce**
1. Use a system with case-sensitive filesystems. e.g. linux
2. Create an avatar with an uppercase name. e.g. 'BestBoi HD'
3. Go to the Avatar Exporter Window
4. Click on 'Export <avatar name>', e.g. 'Export BestBoi HD'
5. Specify export file path
6. See error
7. Check Folder mentioned in error, and find that it contains a '<lowercase avatar name>.avatar' instead of '<avatar name>.avatar', e.g. 'bestboi hd.avatar' instead of 'BestBoi HD.avatar' 

**Expected behavior**
I expect the export to finish without errors, with the output file ending up in the specified location.

**Workarounds**
 - Grab the avatar from the temporary folder yourself
 - Use a lowercase avatar name
 - Export your avatar on Windows

**Comment by nicoco007** [comment]
I've attempted a fix in 361bc36; could you try [this build](https://github.com/nicoco007/BeatSaberCustomAvatars/suites/1740740249/artifacts/33033470) and let me know if it works?

**Comment by kitlith** [comment]
That appears to work, yes. I will comment that since windows filesystems are case sensitive, it would probably be possible to just use the lowercase version in all cases, but this works. :+1:

**Comment by nicoco007** [comment]
Oh yeah, I didn't think about that. Glad it works! This fix will be included in the next release.
