### ISSUE TITLE
Multiplayer Compatible?

### ISSUE THREAD

**Issue by Phantasmal-Rin** [nicoco007/BeatSaberCustomAvatars#87]
Does this display custom avatars in multiplayer? If so does it show me just to me or show to other that have the models and mod installed. Thanks for your contribution the modding community. :)

**Comment by nicoco007** [comment]
Custom Avatars on its own will show your avatar when in multiplayer, but it'll only be visible to you. [Goobwabber](https://github.com/Goobwabber/) is working on [another mod](https://github.com/Goobwabber/MultiplayerAvatars) that works alongside [MultiplayerExtensions](https://github.com/Zingabopp/MultiplayerExtensions) to show other players' avatars when in multiplayer.
