### ISSUE TITLE
can't see listed avatars, previous git issues didn't solve

### ISSUE THREAD

**Issue by LeonTheLeon** [nicoco007/BeatSaberCustomAvatars#88]
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5791919/_latest.log)
please excuse my incompetence.

**Desktop (please complete the following information):**
- Operating system: Windows 10
- Headset and controllers: Oculus Quest 2 (game is running on steam, steam acts it's a Rift S)

**Describe the bug**
-the avatar list does not list any avatars
-the settings to the left are also all locked
-installing the version from[ issue #58 ](https://github.com/nicoco007/BeatSaberCustomAvatars/issues/58#issuecomment-676755378) does not fix it

**Steps to reproduce**
1. install latest version of BeatSaberCustomAvatars
2. install latest version of DynamicOpenVr
3. boot game
4. access avatar menu

**Expected behavior**
the avatars should load

**Screenshots**
https://cdn.discordapp.com/attachments/520592173708738562/797592004556881963/unknown.png
a screenshot of both the empty avatar list and the mostly greyed out settings. (note: i can't change the non-greyed out settings, either.)

edit: https://cdn.discordapp.com/attachments/520592173708738562/797593136800464967/unknown.png
a screenshot of my Steam\steamapps\common\Beat Saber\CustomAvatars folder, showing that i definitely have some avatars.

**Comment by LeonTheLeon** [comment]
please excuse my continued idiocy! i was looking at the wrong menu. it was working all this time. i just didn't see it. i have about 2 brain cells.

**Comment by nicoco007** [comment]
No worries! Glad you were able to figure it out on your own.

**Comment by ArmyHD** [comment]
I got the same issue with the latest version 5.2.3. My avatar list is stuck with loading and I can't do anything.

- Beat Saber version 1.16.1
- Windows 10 Pro
- using Rift S


![Screenshot Beat Saber Custom Avatar menu](https://user-images.githubusercontent.com/42937279/120842403-edb2f400-c56c-11eb-9d41-3f69e7a6dc30.png)


Log:
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/6600309/_latest.log)
