### ISSUE TITLE
Avatars do not track / T-pose with -vrmode oculus

### ISSUE THREAD

**Issue by Jeremiidesu** [nicoco007/BeatSaberCustomAvatars#89]
**Before doing anything else, please attach your latest log to this issue. It should be located at `Logs\_latest.log` in your Beat Saber installation's folder.**
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5811033/_latest.log)

**Desktop (please complete the following information):**
- Operating system: Windows 10 20H2
- Headset and controllers: Oculus Quest over Link, with Oculus Quest controllers

**Describe the bug**
When playing with `-vrmode oculus`, avatars do not track at all. (Using CustomAvatars 5.1.0 and DynamicOpenVR 0.3.4)

**Steps to reproduce**
1. Play with `-vrmode oculus`
2. Look at your avatar (avatar menu mirror, first person, floor reflection...)
3. Move around
4. Notice how the avatar does not follow your movement

**Expected behavior**
Avatars should follow the head and hands' movement.

Playing with SteamVR solves the problem, but `-vrmode oculus` worked before this update.

**Comment by Jeremiidesu** [comment]
After tinkering around for a bit in the repo's history, it seems that commit d6a0fdf03f790840f698119b6a614cc4f90b74d9 is the source of the issue. Removing this commit from the history fixes this issue.

**Comment by nicoco007** [comment]
Thanks for the report! I think I've fixed this in f616a56; could you try out [this build](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5812108/BeatSaberCustomAvatars-f616a56-RELEASE.zip)?

**Comment by Jeremiidesu** [comment]
This build indeed fixes the issue, the avatars now track again. Thank you!
