### ISSUE TITLE
Full body tracking with Vive Trackers calibrates/registers trackers incorrectly. 

### ISSUE THREAD

**Issue by conspiracy0** [nicoco007/BeatSaberCustomAvatars#9]
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4106386/_latest.log)

Whenever I load the game, the vive trackers calibrate in bizarre ways that don't line up to my body at all. I have made sure they are set properly to each corresponding body location in SteamVR, and turn them on after my controllers, L/R/H. 

Here is an example of the phenomenon: https://gfycat.com/excellentnewadeliepenguin

For what its worth, I'm on Index with nothing but SteamVR, and the trackers work fine with VRChat.

**Comment by nicoco007** [comment]
How are you placing your trackers? Are you putting the tracker for your waist in front or on the side of one of your hips? The default Full Body Template avatar expects the waist tracker to be in front with the LED upwards and the feet trackers to be on your toes with the LED forwards. I'm not sure what the expected configuration is for the 2nd avatar you're showing.

Right now, you have to put the trackers where the avatar was made to expect it. This isn't something that is automatically detected (at least for now). Also, full body calibration currently only works properly with avatars that have feet trackers on the toes.

**Comment by conspiracy0** [comment]
Waist in the middle, and then one on each foot. I wasn't aware the LED mattered.

**Comment by nicoco007** [comment]
The orientation of the trackers is important since they track both position and rotation.

For the second avatar you show in the video, the waist tracker should be on your left hip [according to the avatar's ModelSaber page](https://modelsaber.com/Avatars/?id=1564625718&pc).

**Comment by nicoco007** [comment]
Were you able to solve this issue or do you still need help?
