### ISSUE TITLE
Multiplayer Avatar Function

### ISSUE THREAD

**Issue by XCraftTM** [nicoco007/BeatSaberCustomAvatars#90]
I don't know if that would be cool, but maybe add the avatar of beatsaber multiplayer that the user has created ingame.
It is Not Releated to a Problem in any way, I would just find it cool to add and use in livestreams or something.

All avatars that are on ModelSaber are avatars that i don't Like. The Avatar of Beat Saber Multiplayer is better than any of the other ones, i think...

With best regards,
XCraftTM.

**Comment by nicoco007** [comment]
This has actually already been made into its own mod by Naluluna: https://youtu.be/Opbc5-x_D5k (they're Japanese but the installation instructions are also in English).

I'm not sure if I'm willing to build this into Custom Avatars. It would require merging two very different avatar loading/spawning systems. I think it makes more sense to have Custom Avatars and what you're requesting as two separate mods. I'll keep the idea in mind, but for the time being it's not something I'm going to work on.
