### ISSUE TITLE
Floor height adjust 

### ISSUE THREAD

**Issue by fuyushi** [nicoco007/BeatSaberCustomAvatars#91]
Automatic floor height adjust isn't working. Moving myself down a bit in the room adjust will cause the character to permanently crouch slightly. Toggling the function on and off seems to only resize the entire avatar to be bigger, but not actually stretch the legs. Tested this on 3 of my (own) avatars. 
Oculus CV1 using SteamVR

**Comment by nicoco007** [comment]
Are you setting your height in Player Options after changing the game's room adjust? It needs to be set properly for the floor to be moved accurately. If you're using automatic height adjust, turn it off and set your height manually.

**Comment by fuyushi** [comment]
I think you're right, I need to set it again after changing

**Comment by nicoco007** [comment]
Did you get it working or are you still running into problems?
