### ISSUE TITLE
Noodle Map support

### ISSUE THREAD

**Issue by Caruha** [nicoco007/BeatSaberCustomAvatars#95]
Ability to enable so Avatar moves with player in noodle maps.

**Comment by AByakugans** [comment]
Well the avatar (v5.2.0) is moving with me in Camera2 (v0.3.3 ok but the sabers are not moving. There is a fix for VMC but not for Custom avatars... See the begining ic this video: https://www.youtube.com/watch?v=ABq-jV0KrMI

**Comment by Drahy** [comment]
Well the avatar (v5.2.0) is moving with me in Camera2 (v0.3.3) ok but the sabers are not moving. There is a fix for VMC (https://github.com/senacand/RamenFixer/tree/0.1.0) but not for Custom avatars... See the beginning of this video: https://www.youtube.com/watch?v=ABq-jV0KrMI

**Comment by nicoco007** [comment]
Fixed by 4b409ce which will be included in the next release. Thanks for the suggestion!
