### ISSUE TITLE
Avatar menu doesn´t pop up.

### ISSUE THREAD

**Issue by spaffey** [nicoco007/BeatSaberCustomAvatars#97]
log:
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/6211791/_latest.log)

Desktop (please complete the following information):
-Windows 10
-Oculus Quest 2 on Steam VR

Describe the bug:
In the main menu, when I'm trying to open the Avatar Menu, nothing happens. When for example I click on Saber Factory, it opens a separate menu, which it doesn´t do on the Avatar Tab. 

Steps to reproduce:
Open up the game and on the left side is a tab named Avatar by the mods. How I really created the problem is unclear to me.

Expected behavior:
That the Avatar menu would pop up.

Screenshots:
![123456789](https://user-images.githubusercontent.com/81421433/112632473-75c3a180-8e38-11eb-95eb-3847f515f556.jpg)

**Comment by spaffey** [comment]
ok... had not installed the dynamicopenvr.beatsaber. my bad. 
the thing now is that I got plenty of new problems... so my first is, that these all files are missing:
DynamicOpenVR
    **action_manifest.json
    default_bindings_holographic_controllers.json
    default_bindings_knuckles.json
    default_bindings_oculus_touch.json
    default_bindings_vive_controller.json**
![Screenshot_9](https://user-images.githubusercontent.com/81421433/112656424-b0860380-8e51-11eb-8b6b-385c96ae89b5.png)


then my second is, that in my first run in my bindings were on legacy and now its stuck on loading (my steam is set on german):
![123456](https://user-images.githubusercontent.com/81421433/112656555-cdbad200-8e51-11eb-887b-4e0cf883655b.jpg)

I tried reinstalling the mods (Custom Avatars, Dynamicopenvr/.Beatsaber) multiple times but its every time the same problems.
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/6212839/_latest.log)

**Comment by nicoco007** [comment]
You're running extremely old versions of Custom Avatars (you have 5.0.0-beta.7, [the latest is 5.2.1](https://github.com/nicoco007/BeatSaberCustomAvatars/releases/tag/v5.2.1)) and DynamicOpenVR (you have 0.2.0, [the latest is 0.4.0](https://github.com/nicoco007/DynamicOpenVR/releases/tag/v0.4.0)), both of which are meant to run on much older versions of the game and are therefore not compatible with Beat Saber 1.14.0.

If you want to remove DynamicOpenVR.BeatSaber, please [follow the instructions under *Completely Removing DynamicOpenVR* here](https://github.com/nicoco007/DynamicOpenVR/blob/main/TROUBLESHOOTING.md#completely-removing-dynamicopenvr), then reinstall just DynamicOpenVR. Uninstalling it is a bit more involved than just removing the file from the `Plugins` folder, and not removing everything else often leaves your game in a broken state.

**Comment by spaffey** [comment]
ahh, thank you. works now :)
