### ISSUE TITLE
Avatars do not move due to critical tracking exception

### ISSUE THREAD

**Issue by Nearcyan** [nicoco007/BeatSaberCustomAvatars#98]
[log.txt](https://github.com/nicoco007/BeatSaberCustomAvatars/files/6251517/log.txt)

**Desktop:**
- Operating system: Linux 5.9.16, Manjaro
- Headset and controllers: Valve Index

**Describe the bug**
All avatars perform no movement whatsoever

**Steps to reproduce**
1. Install latest BeatSaberCustomAvatars
2. Run BeatSaber and view a custom avatar while moving controllers

**Expected behavior**
Avatar moves along with player

**Additional Information**
Similar to #46, critical `NullReferenceException` occurs at `CustomAvatar.Tracking.OpenVR.OpenVRFacade.GetFloatTrackedDeviceProperty` which prevents all avatar functionality.

**Comment by nicoco007** [comment]
Could you please upload the full log instead of just the specific exception? This is usually related to communication with SteamVR failing, and the exception alone unfortunately doesn't give me enough information.

**Comment by Nearcyan** [comment]
Yes, I had truncated too many lines since the file was 30MB or so, I've included all the lines up to the error this time
[latest_log.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/6251702/latest_log.log)

**Comment by nicoco007** [comment]
Could you try downgrading to [DynamicOpenVR 0.3.5](https://github.com/nicoco007/DynamicOpenVR/releases/tag/v0.3.5)?

**Comment by Nearcyan** [comment]
Replacing both of those files looks to have fixed the issue completely, thank you!
